/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a screenshot/evidence file */
        post: operations["attachment-upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email + password */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register (and sign in) */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List banks */
        get: operations["bank-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's cards */
        get: operations["card-list"];
        put?: never;
        /** Add a card */
        post: operations["card-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a card (holder, tier) */
        put: operations["card-update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/alias-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest a canonical category for a raw menu title (S1) */
        get: operations["cashback-alias-suggestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/canonical-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List canonical categories */
        get: operations["cashback-canonical-list"];
        put?: never;
        /** Create a canonical category */
        post: operations["cashback-canonical-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/category-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record one row of a bank's offer menu */
        post: operations["cashback-category-offer-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/category-offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a menu row (full replace of mutable fields) */
        put: operations["cashback-category-offer-update"];
        post?: never;
        /** Delete a menu row (with its selection) */
        delete: operations["cashback-category-offer-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/helper-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collisions + comparisons + slot tracking for the entry screen */
        get: operations["cashback-helper-context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** «Какой картой платить?» for a canonical category */
        get: operations["cashback-lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/offer-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's selection periods */
        get: operations["cashback-offer-period-list"];
        put?: never;
        /** Open a selection period for a card */
        post: operations["cashback-offer-period-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/offer-periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Selection period with its menu */
        get: operations["cashback-offer-period-get"];
        put?: never;
        post?: never;
        /** Delete a period with its menu and selections */
        delete: operations["cashback-offer-period-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/offer-periods/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a screenshot to the period */
        post: operations["cashback-offer-period-attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/offer-periods/{id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a screenshot (orphaned file is removed) */
        delete: operations["cashback-offer-period-detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/offer-periods/{id}/max-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the period's slot count (null resets to the tier default) */
        put: operations["cashback-offer-period-slots"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Обзор кешбека: лучшие карты по категориям и срез по картам */
        get: operations["cashback-overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/partner-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List partner offers */
        get: operations["cashback-partner-offer-list"];
        put?: never;
        /** Record a partner offer */
        post: operations["cashback-partner-offer-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/partner-offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a partner offer */
        delete: operations["cashback-partner-offer-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cashback programs */
        get: operations["cashback-program-list"];
        put?: never;
        /** Create a cashback program */
        post: operations["cashback-program-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/programs/{id}/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tiers of a program */
        get: operations["cashback-tier-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select an offer (dated event; invariants 1–2 enforced) */
        post: operations["cashback-selection-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/selections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo a selection */
        delete: operations["cashback-selection-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cashback/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a program tier (client level) */
        post: operations["cashback-tier-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Attachment-uploadResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Attachment-uploadResponse.json
             */
            readonly $schema?: string;
            filename: string;
            id: string;
        };
        "Auth-loginRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Auth-loginRequest.json
             */
            readonly $schema?: string;
            /** Format: email */
            email: string;
            password: string;
        };
        "Auth-registerRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Auth-registerRequest.json
             */
            readonly $schema?: string;
            display_name: string;
            /** Format: email */
            email: string;
            password: string;
            username: string;
        };
        BankDTO: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        CanonicalCategoryDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CanonicalCategoryDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            slug: string;
            title_ru: string;
        };
        "Card-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Card-createRequest.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            bank_id: number;
            /** @description whose plastic this is («Мама»); omit for your own */
            holder_label?: string;
            /** Format: int32 */
            last_4_digits: number;
            /** @enum {string} */
            payment_system: "visa" | "mastercard" | "mir" | "unionpay" | "american_express";
            /** Format: int64 */
            program_tier_id?: number;
        };
        "Card-updateRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Card-updateRequest.json
             */
            readonly $schema?: string;
            holder_label?: string;
            /** Format: int64 */
            program_tier_id?: number;
        };
        CardDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CardDTO.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            bank_id: number;
            bank_name?: string;
            holder_label?: string;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            last_4_digits: number;
            payment_system: string;
            /** Format: int64 */
            program_tier_id?: number;
        };
        "Cashback-alias-suggestionResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-alias-suggestionResponse.json
             */
            readonly $schema?: string;
            suggestion: components["schemas"]["CanonicalCategoryDTO"];
        };
        "Cashback-canonical-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-canonical-createRequest.json
             */
            readonly $schema?: string;
            slug: string;
            title_ru: string;
        };
        "Cashback-category-offer-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-category-offer-createRequest.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            canonical_category_id?: number;
            /**
             * @default regular
             * @enum {string}
             */
            kind: "regular" | "special" | "base";
            notes?: string;
            /** Format: int64 */
            offer_period_id: number;
            percent?: string;
            raw_title: string;
        };
        "Cashback-helper-contextResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-helper-contextResponse.json
             */
            readonly $schema?: string;
            card_label: string;
            /**
             * Format: int32
             * @description effective limit: period override, else tier default
             */
            max_categories?: number;
            /** Format: int32 */
            max_categories_override?: number;
            /** Format: int64 */
            offer_period_id: number;
            rows: components["schemas"]["HelperRowDTO"][] | null;
            /** Format: int64 */
            slots_used: number;
        };
        "Cashback-lookupResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-lookupResponse.json
             */
            readonly $schema?: string;
            category: components["schemas"]["CanonicalCategoryDTO"];
            date: string;
            /** @description base rates — pay with these when nothing ranks */
            fallback?: components["schemas"]["LookupEntryDTO"][] | null;
            message?: string;
            partner?: components["schemas"]["PartnerOfferDTO"][] | null;
            ranked: components["schemas"]["LookupEntryDTO"][] | null;
            special?: components["schemas"]["LookupEntryDTO"][] | null;
        };
        "Cashback-offer-period-attachRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-offer-period-attachRequest.json
             */
            readonly $schema?: string;
            attachment_id: string;
        };
        "Cashback-offer-period-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-offer-period-createRequest.json
             */
            readonly $schema?: string;
            attachment_ids?: string[] | null;
            /** Format: int32 */
            card_id: number;
            /** Format: date */
            period_end: string;
            /** Format: date */
            period_start: string;
        };
        "Cashback-offer-period-getResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-offer-period-getResponse.json
             */
            readonly $schema?: string;
            attachment_ids: string[] | null;
            bank_name: string;
            /** Format: int32 */
            card_id: number;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            max_categories_override?: number;
            offers: components["schemas"]["CategoryOfferDTO"][] | null;
            period_end: string;
            period_start: string;
        };
        "Cashback-offer-period-slotsRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-offer-period-slotsRequest.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            value: number | null;
        };
        "Cashback-overviewResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-overviewResponse.json
             */
            readonly $schema?: string;
            base?: components["schemas"]["OverviewBaseDTO"];
            cards: components["schemas"]["OverviewCardDTO"][] | null;
            categories: components["schemas"]["OverviewCategoryDTO"][] | null;
            date: string;
            /** Format: int32 */
            selection_opens_day?: number;
        };
        "Cashback-partner-offer-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-partner-offer-createRequest.json
             */
            readonly $schema?: string;
            attachment_ids?: string[] | null;
            /** Format: int32 */
            bank_id: number;
            cap_value?: string;
            /** Format: int32 */
            card_id?: number;
            merchant_title: string;
            notes?: string;
            percent?: string;
            /** Format: date */
            valid_from?: string;
            /** Format: date */
            valid_to?: string;
        };
        "Cashback-selection-createRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-selection-createRequest.json
             */
            readonly $schema?: string;
            backfill_override?: boolean;
            /** Format: int64 */
            category_offer_id: number;
            /** Format: date-time */
            selected_at?: string;
        };
        "Cashback-selection-createResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cashback-selection-createResponse.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            category_offer_id: number;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            selected_at: string;
        };
        CategoryOfferBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CategoryOfferBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            canonical_category_id?: number;
            /**
             * @default regular
             * @enum {string}
             */
            kind: "regular" | "special" | "base";
            notes?: string;
            percent?: string;
            raw_title: string;
        };
        CategoryOfferDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CategoryOfferDTO.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            canonical_category_id?: number;
            /** Format: int64 */
            id: number;
            kind: string;
            notes?: string;
            /** Format: int64 */
            offer_period_id: number;
            percent?: string;
            raw_title: string;
            /** Format: date-time */
            selected_at?: string;
            /** Format: int64 */
            selection_id?: number;
        };
        CollisionDTO: {
            bank_name: string;
            cap_note?: string;
            card_label: string;
            holder_label?: string;
            message: string;
            percent?: string;
        };
        ComparisonDTO: {
            bank_name: string;
            card_label: string;
            percent?: string;
            raw_title: string;
            selected: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FormFile: {
            ContentType: string;
            Filename: string;
            IsSet: boolean;
            /** Format: int64 */
            Size: number;
        };
        HelperRowDTO: {
            /** Format: int64 */
            category_offer_id: number;
            collisions?: components["schemas"]["CollisionDTO"][] | null;
            comparisons?: components["schemas"]["ComparisonDTO"][] | null;
            kind: string;
            percent?: string;
            raw_title: string;
            selected: boolean;
        };
        LookupEntryDTO: {
            bank_name: string;
            cap_per_category?: string;
            cap_scope?: string;
            cap_value?: string;
            card_label: string;
            currency_kind: string;
            holder_label?: string;
            percent?: string;
            period_end: string;
            period_start: string;
            points_label?: string;
        };
        OfferPeriodDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OfferPeriodDTO.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            card_id: number;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            max_categories_override?: number;
            period_end: string;
            period_start: string;
        };
        OfferPeriodListItem: {
            bank_name: string;
            /** Format: int32 */
            card_id: number;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            max_categories_override?: number;
            period_end: string;
            period_start: string;
        };
        OverviewBaseDTO: {
            best: components["schemas"]["LookupEntryDTO"];
            /** Format: int64 */
            others_count: number;
        };
        OverviewCardDTO: {
            /** Format: int32 */
            bank_id: number;
            bank_name: string;
            cap_per_category?: string;
            cap_scope?: string;
            cap_value?: string;
            /** Format: int32 */
            card_id: number;
            currency_kind: string;
            holder_label?: string;
            is_paid_tier?: boolean;
            /** Format: int32 */
            last_4_digits: number;
            /** Format: int32 */
            max_categories?: number;
            period_end?: string;
            /** Format: int64 */
            period_id?: number;
            period_start?: string;
            points_label?: string;
            selected: components["schemas"]["OverviewChipDTO"][] | null;
            selection_mode?: string;
            /** Format: int64 */
            slots_used: number;
            specials?: components["schemas"]["OverviewChipDTO"][] | null;
            tier_name?: string;
        };
        OverviewCategoryDTO: {
            best: components["schemas"]["LookupEntryDTO"];
            /** Format: int64 */
            category_id: number;
            /** Format: int64 */
            others_count: number;
            slug: string;
            title_ru: string;
        };
        OverviewChipDTO: {
            /** Format: int64 */
            offer_id: number;
            percent?: string;
            raw_title: string;
        };
        PartnerOfferDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PartnerOfferDTO.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            bank_id: number;
            bank_name?: string;
            cap_value?: string;
            /** Format: int32 */
            card_id?: number;
            /** Format: int64 */
            id: number;
            merchant_title: string;
            notes?: string;
            percent?: string;
            valid_from?: string;
            valid_to?: string;
        };
        ProgramBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProgramBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            bank_id: number;
            /** @enum {string} */
            currency_kind: "rub" | "points";
            name: string;
            notes?: string;
            /** @enum {string} */
            period_type: "calendar_month" | "quarter" | "week" | "rolling";
            points_label?: string;
            /** @enum {string} */
            selection_mode: "atomic" | "incremental";
            /** Format: int32 */
            selection_opens_day?: number;
        };
        ProgramDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProgramDTO.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            bank_id: number;
            bank_name?: string;
            currency_kind: string;
            /** Format: int64 */
            id: number;
            name: string;
            notes?: string;
            period_type: string;
            points_label?: string;
            selection_mode: string;
            /** Format: int32 */
            selection_opens_day?: number;
        };
        TierBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TierBody.json
             */
            readonly $schema?: string;
            base_percent?: string;
            cap_per_category?: string;
            /**
             * @default total
             * @enum {string}
             */
            cap_scope: "total" | "per_category" | "both";
            cap_value?: string;
            is_paid_subscription?: boolean;
            /** Format: int32 */
            max_categories?: number;
            name: string;
            notes?: string;
            /** Format: int64 */
            program_id: number;
        };
        TierDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TierDTO.json
             */
            readonly $schema?: string;
            base_percent?: string;
            cap_per_category?: string;
            cap_scope: string;
            cap_value?: string;
            /** Format: int64 */
            id: number;
            is_paid_subscription: boolean;
            /** Format: int32 */
            max_categories?: number;
            name: string;
            notes?: string;
            /** Format: int64 */
            program_id: number;
        };
        UserDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UserDTO.json
             */
            readonly $schema?: string;
            display_name: string;
            email: string;
            id: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "attachment-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment-uploadResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Auth-loginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Auth-registerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "bank-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "card-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "card-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Card-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "card-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Card-updateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-alias-suggestion": {
        parameters: {
            query: {
                offer_period_id: number;
                raw_title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-alias-suggestionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-canonical-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalCategoryDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-canonical-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-canonical-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalCategoryDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-category-offer-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-category-offer-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOfferDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-category-offer-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryOfferBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOfferDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-category-offer-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-helper-context": {
        parameters: {
            query: {
                offer_period_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-helper-contextResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-lookup": {
        parameters: {
            query: {
                /** @description canonical category slug */
                category: string;
                /** @description YYYY-MM-DD; defaults to today */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-lookupResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-list": {
        parameters: {
            query?: {
                card_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPeriodListItem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-offer-period-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPeriodDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-offer-period-getResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-attach": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-offer-period-attachRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-detach": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-offer-period-slots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-offer-period-slotsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPeriodDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-overview": {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD; defaults to today */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-overviewResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-partner-offer-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOfferDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-partner-offer-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-partner-offer-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOfferDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-partner-offer-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-program-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-program-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-tier-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierDTO"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-selection-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cashback-selection-createRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cashback-selection-createResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-selection-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cashback-tier-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
