package seed

// MCC seed: the dictionary only. Membership (bank_category_mcc) left the
// seed with the ADR-0004 import: category→MCC compositions are hard-parsed
// bank data, enter each deployment at run time via `sharespences
// mcc-import <snapshot.json>` (diff + mcc_change journal), and a fresh
// install answers MCC lookups with nothing until its first import — the
// point_of_sale precedent. The dictionary stays seeded: it is generic
// public reference data (mcc-codes.ru), regenerated by
// utils/mcc_dict_regen.py — never hand-edit the CSV here.

import (
	"bytes"
	"context"
	_ "embed"
	"encoding/csv"
	"fmt"
	"strconv"

	"github.com/jackc/pgx/v5/pgxpool"
)

//go:embed data/mcc_codes.csv
var mccCodesCSV []byte

func seedMCC(ctx context.Context, pool *pgxpool.Pool) error {
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("seed mcc: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Dictionary — unconditional refresh (knowledge-derived, like
	// emoji/brand colors). Import-added glosses (snapshot `dictionary`
	// sections) insert codes this CSV lacks and are never overwritten here:
	// the upsert only touches codes the CSV names.
	dict, err := readCSV(mccCodesCSV, 3)
	if err != nil {
		return fmt.Errorf("seed mcc: dictionary csv: %w", err)
	}
	for _, rec := range dict {
		code, err := strconv.ParseInt(rec[0], 10, 16)
		if err != nil {
			return fmt.Errorf("seed mcc: bad dictionary code %q: %w", rec[0], err)
		}
		if _, err := tx.Exec(ctx, `
			insert into mcc (code, name, description)
			values ($1, $2, nullif($3, ''))
			on conflict (code) do update set name = excluded.name, description = excluded.description`,
			int16(code), rec[1], rec[2]); err != nil {
			return fmt.Errorf("seed mcc: dictionary %s: %w", rec[0], err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("seed mcc: commit: %w", err)
	}
	return nil
}

func readCSV(data []byte, fields int) ([][]string, error) {
	r := csv.NewReader(bytes.NewReader(data))
	// Semicolon-delimited, matching the utils/ pipeline these files come out of
	// (category_mcc-constructor, mcc_dict-parser and mcc_dict_regen all read
	// ';'). Russian descriptions are full of commas, so a comma separator quoted
	// half the dictionary — 540 of 1078 rows, against 150 now. It also opens
	// correctly in a ru-locale spreadsheet, where ';' is the field separator.
	r.Comma = ';'
	r.FieldsPerRecord = fields
	recs, err := r.ReadAll()
	if err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, fmt.Errorf("empty csv")
	}
	return recs[1:], nil // drop header
}
