// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCounts = `-- name: AdminCounts :one

select (select count(*) from bank)                                  as banks,
       (select count(*) from canonical_category)                    as canonical_categories,
       (select count(*) from bank_category)                         as bank_categories,
       (select count(*) from bank_category where is_custom)         as custom_bank_categories,
       (select count(*) from bank_category_alias)                   as aliases,
       (select count(*) from cashback_program)                      as programs,
       (select count(*) from program_tier)                          as tiers,
       (select count(*) from mcc)                                   as mcc_codes,
       (select count(*) from bank_category_mcc)                     as mcc_links,
       (select count(*) from mcc_change)                            as mcc_changes,
       (select count(*) from point_of_sale)                         as points_of_sale,
       (select count(*) from "user")                                as users,
       (select count(*) from attachment)                            as attachments
`

type AdminCountsRow struct {
	Banks                int64
	CanonicalCategories  int64
	BankCategories       int64
	CustomBankCategories int64
	Aliases              int64
	Programs             int64
	Tiers                int64
	MccCodes             int64
	MccLinks             int64
	MccChanges           int64
	PointsOfSale         int64
	Users                int64
	Attachments          int64
}

// Admin sidecar queries (ADR-0008). Operator tooling spans module tables by
// nature — the seam rule is relaxed here the same way it is for seed and
// import-pos. Write queries exist only for what seed does NOT own: custom
// bank_category rows (is_custom guard in SQL), the MCC dictionary and
// category↔MCC links outside the seed CSVs (coverage guard in the service),
// the mcc_change journal, and point_of_sale. `location` (PostGIS geometry)
// is deliberately never selected or written — v1 has no map widget.
func (q *Queries) AdminCounts(ctx context.Context) (AdminCountsRow, error) {
	row := q.db.QueryRow(ctx, adminCounts)
	var i AdminCountsRow
	err := row.Scan(
		&i.Banks,
		&i.CanonicalCategories,
		&i.BankCategories,
		&i.CustomBankCategories,
		&i.Aliases,
		&i.Programs,
		&i.Tiers,
		&i.MccCodes,
		&i.MccLinks,
		&i.MccChanges,
		&i.PointsOfSale,
		&i.Users,
		&i.Attachments,
	)
	return i, err
}

const adminCreateMCC = `-- name: AdminCreateMCC :one
insert into mcc (code, name, description)
values ($1, $2, $3)
returning code, name, description
`

type AdminCreateMCCParams struct {
	Code        int16
	Name        string
	Description *string
}

func (q *Queries) AdminCreateMCC(ctx context.Context, arg AdminCreateMCCParams) (Mcc, error) {
	row := q.db.QueryRow(ctx, adminCreateMCC, arg.Code, arg.Name, arg.Description)
	var i Mcc
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const adminCreateMCCChange = `-- name: AdminCreateMCCChange :one
insert into mcc_change (bank_id, bank_category_id, category_title, mcc_code, action, source, note)
values ($1, $2, $3, $4, $5, $6, $7)
returning id
`

type AdminCreateMCCChangeParams struct {
	BankID         int32
	BankCategoryID *int64
	CategoryTitle  string
	MccCode        *int16
	Action         MccChangeAction
	Source         string
	Note           *string
}

func (q *Queries) AdminCreateMCCChange(ctx context.Context, arg AdminCreateMCCChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCreateMCCChange,
		arg.BankID,
		arg.BankCategoryID,
		arg.CategoryTitle,
		arg.MccCode,
		arg.Action,
		arg.Source,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminCreatePOS = `-- name: AdminCreatePOS :one
insert into point_of_sale (name, merchant_title, mcc_code, type, address)
values ($1, $2, $3, $4, $5)
returning id
`

type AdminCreatePOSParams struct {
	Name          string
	MerchantTitle *string
	MccCode       *int16
	Type          NullPointOfSaleType
	Address       *string
}

func (q *Queries) AdminCreatePOS(ctx context.Context, arg AdminCreatePOSParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, adminCreatePOS,
		arg.Name,
		arg.MerchantTitle,
		arg.MccCode,
		arg.Type,
		arg.Address,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const adminDeleteBankCategoryMCC = `-- name: AdminDeleteBankCategoryMCC :execrows
delete
from bank_category_mcc
where bank_category_id = $1
  and mcc_code = $2
`

type AdminDeleteBankCategoryMCCParams struct {
	BankCategoryID int64
	MccCode        int16
}

func (q *Queries) AdminDeleteBankCategoryMCC(ctx context.Context, arg AdminDeleteBankCategoryMCCParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteBankCategoryMCC, arg.BankCategoryID, arg.MccCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteCustomBankCategory = `-- name: AdminDeleteCustomBankCategory :execrows
delete
from bank_category
where id = $1
  and is_custom
`

func (q *Queries) AdminDeleteCustomBankCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteCustomBankCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteMCC = `-- name: AdminDeleteMCC :execrows
delete
from mcc
where code = $1
`

func (q *Queries) AdminDeleteMCC(ctx context.Context, code int16) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteMCC, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteMCCChange = `-- name: AdminDeleteMCCChange :execrows
delete
from mcc_change
where id = $1
`

func (q *Queries) AdminDeleteMCCChange(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteMCCChange, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeletePOS = `-- name: AdminDeletePOS :execrows
delete
from point_of_sale
where id = $1
`

func (q *Queries) AdminDeletePOS(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeletePOS, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetBankCategoryWithBank = `-- name: AdminGetBankCategoryWithBank :one
select bc.id, bc.bank_id, b.name as bank_name, bc.title, bc.is_custom
from bank_category bc
         join bank b on b.id = bc.bank_id
where bc.id = $1
`

type AdminGetBankCategoryWithBankRow struct {
	ID       int64
	BankID   int32
	BankName string
	Title    string
	IsCustom bool
}

func (q *Queries) AdminGetBankCategoryWithBank(ctx context.Context, id int64) (AdminGetBankCategoryWithBankRow, error) {
	row := q.db.QueryRow(ctx, adminGetBankCategoryWithBank, id)
	var i AdminGetBankCategoryWithBankRow
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.BankName,
		&i.Title,
		&i.IsCustom,
	)
	return i, err
}

const adminListAliases = `-- name: AdminListAliases :many
select a.bank_id,
       b.name      as bank_name,
       a.raw_title,
       a.canonical_category_id,
       cc.slug     as canonical_slug,
       cc.title_ru as canonical_title
from bank_category_alias a
         join bank b on b.id = a.bank_id
         join canonical_category cc on cc.id = a.canonical_category_id
order by cc.slug, b.name, a.raw_title
`

type AdminListAliasesRow struct {
	BankID              int32
	BankName            string
	RawTitle            string
	CanonicalCategoryID int64
	CanonicalSlug       string
	CanonicalTitle      string
}

func (q *Queries) AdminListAliases(ctx context.Context) ([]AdminListAliasesRow, error) {
	rows, err := q.db.Query(ctx, adminListAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAliasesRow
	for rows.Next() {
		var i AdminListAliasesRow
		if err := rows.Scan(
			&i.BankID,
			&i.BankName,
			&i.RawTitle,
			&i.CanonicalCategoryID,
			&i.CanonicalSlug,
			&i.CanonicalTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListBankCategories = `-- name: AdminListBankCategories :many
select bc.id,
       bc.bank_id,
       b.name      as bank_name,
       bc.title,
       bc.canonical_category_id,
       cc.slug     as canonical_slug,
       cc.title_ru as canonical_title,
       bc.kind,
       bc.emoji,
       bc.is_custom,
       bc.active,
       (select count(*) from bank_category_mcc m where m.bank_category_id = bc.id) as mcc_count
from bank_category bc
         join bank b on b.id = bc.bank_id
         left join canonical_category cc on cc.id = bc.canonical_category_id
where bc.bank_id = $1 or $1 is null
order by b.name, bc.kind, bc.title
`

type AdminListBankCategoriesRow struct {
	ID                  int64
	BankID              int32
	BankName            string
	Title               string
	CanonicalCategoryID *int64
	CanonicalSlug       *string
	CanonicalTitle      *string
	Kind                CashbackOfferKind
	Emoji               *string
	IsCustom            bool
	Active              bool
	MccCount            int64
}

func (q *Queries) AdminListBankCategories(ctx context.Context, bankID *int32) ([]AdminListBankCategoriesRow, error) {
	rows, err := q.db.Query(ctx, adminListBankCategories, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListBankCategoriesRow
	for rows.Next() {
		var i AdminListBankCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.Title,
			&i.CanonicalCategoryID,
			&i.CanonicalSlug,
			&i.CanonicalTitle,
			&i.Kind,
			&i.Emoji,
			&i.IsCustom,
			&i.Active,
			&i.MccCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListBankCategoryMCC = `-- name: AdminListBankCategoryMCC :many
select bcm.mcc_code,
       m.name as mcc_name,
       bcm.note
from bank_category_mcc bcm
         join mcc m on m.code = bcm.mcc_code
where bcm.bank_category_id = $1
order by bcm.mcc_code
`

type AdminListBankCategoryMCCRow struct {
	MccCode int16
	MccName string
	Note    *string
}

func (q *Queries) AdminListBankCategoryMCC(ctx context.Context, bankCategoryID int64) ([]AdminListBankCategoryMCCRow, error) {
	rows, err := q.db.Query(ctx, adminListBankCategoryMCC, bankCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListBankCategoryMCCRow
	for rows.Next() {
		var i AdminListBankCategoryMCCRow
		if err := rows.Scan(&i.MccCode, &i.MccName, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMCC = `-- name: AdminListMCC :many
select code,
       name,
       description,
       count(*) over ()::bigint as total
from mcc
where $1::text = ''
   or name ilike '%' || $1::text || '%'
   or lpad(code::text, 4, '0') like $1::text || '%'
order by code
limit $3 offset $2
`

type AdminListMCCParams struct {
	Query   string
	Skip    int32
	MaxRows int32
}

type AdminListMCCRow struct {
	Code        int16
	Name        string
	Description *string
	Total       int64
}

func (q *Queries) AdminListMCC(ctx context.Context, arg AdminListMCCParams) ([]AdminListMCCRow, error) {
	rows, err := q.db.Query(ctx, adminListMCC, arg.Query, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMCCRow
	for rows.Next() {
		var i AdminListMCCRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMCCChanges = `-- name: AdminListMCCChanges :many
select mc.id,
       mc.bank_id,
       b.name as bank_name,
       mc.bank_category_id,
       mc.category_title,
       mc.mcc_code,
       mc.action,
       mc.noted_at,
       mc.source,
       mc.note,
       count(*) over ()::bigint as total
from mcc_change mc
         join bank b on b.id = mc.bank_id
order by mc.noted_at desc, mc.id desc
limit $2 offset $1
`

type AdminListMCCChangesParams struct {
	Skip    int32
	MaxRows int32
}

type AdminListMCCChangesRow struct {
	ID             int64
	BankID         int32
	BankName       string
	BankCategoryID *int64
	CategoryTitle  string
	MccCode        *int16
	Action         MccChangeAction
	NotedAt        time.Time
	Source         string
	Note           *string
	Total          int64
}

func (q *Queries) AdminListMCCChanges(ctx context.Context, arg AdminListMCCChangesParams) ([]AdminListMCCChangesRow, error) {
	rows, err := q.db.Query(ctx, adminListMCCChanges, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMCCChangesRow
	for rows.Next() {
		var i AdminListMCCChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.BankCategoryID,
			&i.CategoryTitle,
			&i.MccCode,
			&i.Action,
			&i.NotedAt,
			&i.Source,
			&i.Note,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSearchPOS = `-- name: AdminSearchPOS :many
select id,
       name,
       merchant_title,
       mcc_code,
       type,
       address,
       confirmations,
       created_at,
       last_confirmed_at,
       count(*) over ()::bigint as total
from point_of_sale
where $1::text = ''
   or name ilike '%' || $1::text || '%'
   or merchant_title ilike '%' || $1::text || '%'
order by confirmations desc nulls last, name, id
limit $3 offset $2
`

type AdminSearchPOSParams struct {
	Query   string
	Skip    int32
	MaxRows int32
}

type AdminSearchPOSRow struct {
	ID              uuid.UUID
	Name            string
	MerchantTitle   *string
	MccCode         *int16
	Type            NullPointOfSaleType
	Address         *string
	Confirmations   *int64
	CreatedAt       time.Time
	LastConfirmedAt *time.Time
	Total           int64
}

func (q *Queries) AdminSearchPOS(ctx context.Context, arg AdminSearchPOSParams) ([]AdminSearchPOSRow, error) {
	rows, err := q.db.Query(ctx, adminSearchPOS, arg.Query, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSearchPOSRow
	for rows.Next() {
		var i AdminSearchPOSRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.Type,
			&i.Address,
			&i.Confirmations,
			&i.CreatedAt,
			&i.LastConfirmedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateCustomBankCategory = `-- name: AdminUpdateCustomBankCategory :one
update bank_category
set title                 = $2,
    canonical_category_id = $3,
    kind                  = $4,
    emoji                 = $5,
    active                = $6
where id = $1
  and is_custom
returning id, bank_id, title, canonical_category_id, kind, emoji, is_custom, active
`

type AdminUpdateCustomBankCategoryParams struct {
	ID                  int64
	Title               string
	CanonicalCategoryID *int64
	Kind                CashbackOfferKind
	Emoji               *string
	Active              bool
}

func (q *Queries) AdminUpdateCustomBankCategory(ctx context.Context, arg AdminUpdateCustomBankCategoryParams) (BankCategory, error) {
	row := q.db.QueryRow(ctx, adminUpdateCustomBankCategory,
		arg.ID,
		arg.Title,
		arg.CanonicalCategoryID,
		arg.Kind,
		arg.Emoji,
		arg.Active,
	)
	var i BankCategory
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.CanonicalCategoryID,
		&i.Kind,
		&i.Emoji,
		&i.IsCustom,
		&i.Active,
	)
	return i, err
}

const adminUpdateMCC = `-- name: AdminUpdateMCC :one
update mcc
set name        = $2,
    description = $3
where code = $1
returning code, name, description
`

type AdminUpdateMCCParams struct {
	Code        int16
	Name        string
	Description *string
}

func (q *Queries) AdminUpdateMCC(ctx context.Context, arg AdminUpdateMCCParams) (Mcc, error) {
	row := q.db.QueryRow(ctx, adminUpdateMCC, arg.Code, arg.Name, arg.Description)
	var i Mcc
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const adminUpdatePOS = `-- name: AdminUpdatePOS :one
update point_of_sale
set name              = $2,
    merchant_title    = $3,
    mcc_code          = $4,
    type              = $5,
    address           = $6
where id = $1
returning id
`

type AdminUpdatePOSParams struct {
	ID            uuid.UUID
	Name          string
	MerchantTitle *string
	MccCode       *int16
	Type          NullPointOfSaleType
	Address       *string
}

func (q *Queries) AdminUpdatePOS(ctx context.Context, arg AdminUpdatePOSParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, adminUpdatePOS,
		arg.ID,
		arg.Name,
		arg.MerchantTitle,
		arg.MccCode,
		arg.Type,
		arg.Address,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const adminUpsertBankCategoryMCC = `-- name: AdminUpsertBankCategoryMCC :exec
insert into bank_category_mcc (bank_category_id, mcc_code, note)
values ($1, $2, $3)
on conflict (bank_category_id, mcc_code) do update set note = excluded.note
`

type AdminUpsertBankCategoryMCCParams struct {
	BankCategoryID int64
	MccCode        int16
	Note           *string
}

func (q *Queries) AdminUpsertBankCategoryMCC(ctx context.Context, arg AdminUpsertBankCategoryMCCParams) error {
	_, err := q.db.Exec(ctx, adminUpsertBankCategoryMCC, arg.BankCategoryID, arg.MccCode, arg.Note)
	return err
}
