// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
insert into attachment (id, filename, media_type, user_id)
values ($1, $2, $3, $4)
returning id, filename, media_type, user_id
`

type CreateAttachmentParams struct {
	ID        uuid.UUID
	Filename  string
	MediaType *string
	UserID    *uuid.UUID
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.Filename,
		arg.MediaType,
		arg.UserID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MediaType,
		&i.UserID,
	)
	return i, err
}

const getAttachmentForUser = `-- name: GetAttachmentForUser :one
select id, filename, media_type, user_id
from attachment
where id = $1
  and user_id = $2
`

type GetAttachmentForUserParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) GetAttachmentForUser(ctx context.Context, arg GetAttachmentForUserParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentForUser, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MediaType,
		&i.UserID,
	)
	return i, err
}
