// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
insert into bank_card (bank_id, user_id, last_4_digits, payment_system, program_tier_id)
values ($1, $2, $3, $4, $5)
returning id, bank_id, user_id, last_4_digits, payment_system, image_filename, program_tier_id
`

type CreateCardParams struct {
	BankID        int16
	UserID        uuid.UUID
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ProgramTierID *int64
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (BankCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.BankID,
		arg.UserID,
		arg.Last4Digits,
		arg.PaymentSystem,
		arg.ProgramTierID,
	)
	var i BankCard
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.UserID,
		&i.Last4Digits,
		&i.PaymentSystem,
		&i.ImageFilename,
		&i.ProgramTierID,
	)
	return i, err
}

const getBankByName = `-- name: GetBankByName :one
select id, name, logo_filename, color_hex
from bank
where name = $1
`

func (q *Queries) GetBankByName(ctx context.Context, name string) (Bank, error) {
	row := q.db.QueryRow(ctx, getBankByName, name)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoFilename,
		&i.ColorHex,
	)
	return i, err
}

const getCardForUser = `-- name: GetCardForUser :one
select bc.id, bc.bank_id, bc.user_id, bc.last_4_digits, bc.payment_system, bc.image_filename, bc.program_tier_id, b.name as bank_name
from bank_card bc
         join bank b on b.id = bc.bank_id
where bc.id = $1
  and bc.user_id = $2
`

type GetCardForUserParams struct {
	ID     int32
	UserID uuid.UUID
}

type GetCardForUserRow struct {
	ID            int32
	BankID        int16
	UserID        uuid.UUID
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ImageFilename *string
	ProgramTierID *int64
	BankName      string
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.ID, arg.UserID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.UserID,
		&i.Last4Digits,
		&i.PaymentSystem,
		&i.ImageFilename,
		&i.ProgramTierID,
		&i.BankName,
	)
	return i, err
}

const listBanks = `-- name: ListBanks :many
select id, name, logo_filename, color_hex
from bank
order by id
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.Query(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoFilename,
			&i.ColorHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForUser = `-- name: ListCardsForUser :many
select bc.id, bc.bank_id, bc.user_id, bc.last_4_digits, bc.payment_system, bc.image_filename, bc.program_tier_id, b.name as bank_name
from bank_card bc
         join bank b on b.id = bc.bank_id
where bc.user_id = $1
order by bc.id
`

type ListCardsForUserRow struct {
	ID            int32
	BankID        int16
	UserID        uuid.UUID
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ImageFilename *string
	ProgramTierID *int64
	BankName      string
}

func (q *Queries) ListCardsForUser(ctx context.Context, userID uuid.UUID) ([]ListCardsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsForUserRow
	for rows.Next() {
		var i ListCardsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.UserID,
			&i.Last4Digits,
			&i.PaymentSystem,
			&i.ImageFilename,
			&i.ProgramTierID,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
