// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBankClient = `-- name: CreateBankClient :one
insert into bank_client (user_id, bank_id, label, program_tier_id)
values ($1, $2, $3, $4)
returning id, user_id, bank_id, label, program_tier_id
`

type CreateBankClientParams struct {
	UserID        uuid.UUID
	BankID        int32
	Label         *string
	ProgramTierID *int64
}

func (q *Queries) CreateBankClient(ctx context.Context, arg CreateBankClientParams) (BankClient, error) {
	row := q.db.QueryRow(ctx, createBankClient,
		arg.UserID,
		arg.BankID,
		arg.Label,
		arg.ProgramTierID,
	)
	var i BankClient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.Label,
		&i.ProgramTierID,
	)
	return i, err
}

const createCard = `-- name: CreateCard :one
insert into bank_card (bank_client_id, last_4_digits, payment_system)
select cl.id, $1::integer, $2::payment_system
from bank_client cl
where cl.id = $3
  and cl.user_id = $4
returning id, last_4_digits, payment_system, image_filename, bank_client_id
`

type CreateCardParams struct {
	Last4Digits   int32
	PaymentSystem PaymentSystem
	BankClientID  int64
	UserID        uuid.UUID
}

// CreateCard authorizes and derives in one statement: inserting through a
// select on the user's own bank_client returns 0 rows (pgx.ErrNoRows → 404)
// when the client does not exist or belongs to someone else.
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (BankCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Last4Digits,
		arg.PaymentSystem,
		arg.BankClientID,
		arg.UserID,
	)
	var i BankCard
	err := row.Scan(
		&i.ID,
		&i.Last4Digits,
		&i.PaymentSystem,
		&i.ImageFilename,
		&i.BankClientID,
	)
	return i, err
}

const deleteBankClientForUser = `-- name: DeleteBankClientForUser :execrows
with gone_cards as (
    delete from bank_card bc
        where bc.bank_client_id in (select cl.id
                                    from bank_client cl
                                    where cl.id = $1
                                      and cl.user_id = $2))
delete
from bank_client
where bank_client.id = $1
  and bank_client.user_id = $2
`

type DeleteBankClientForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

// DeleteBankClientForUser removes the client and its cards in one atomic
// statement (RI fires at statement end). КБ history — offer_period /
// partner_offer rows, plain FKs to bank_client — makes the whole statement
// fail with 23503, which the handler maps to 409; no cross-module read.
func (q *Queries) DeleteBankClientForUser(ctx context.Context, arg DeleteBankClientForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBankClientForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCardForUser = `-- name: DeleteCardForUser :execrows
delete
from bank_card bc
    using bank_client cl
where bc.id = $1
  and cl.id = bc.bank_client_id
  and cl.user_id = $2
`

type DeleteCardForUserParams struct {
	ID     int32
	UserID uuid.UUID
}

func (q *Queries) DeleteCardForUser(ctx context.Context, arg DeleteCardForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBankByName = `-- name: GetBankByName :one
select id, name, logo_filename, color_hex
from bank
where name = $1
`

func (q *Queries) GetBankByName(ctx context.Context, name string) (Bank, error) {
	row := q.db.QueryRow(ctx, getBankByName, name)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoFilename,
		&i.ColorHex,
	)
	return i, err
}

const getBankClientForUser = `-- name: GetBankClientForUser :one
select cl.id, cl.user_id, cl.bank_id, cl.label, cl.program_tier_id, b.name as bank_name
from bank_client cl
         join bank b on b.id = cl.bank_id
where cl.id = $1
  and cl.user_id = $2
`

type GetBankClientForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetBankClientForUserRow struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	Label         *string
	ProgramTierID *int64
	BankName      string
}

func (q *Queries) GetBankClientForUser(ctx context.Context, arg GetBankClientForUserParams) (GetBankClientForUserRow, error) {
	row := q.db.QueryRow(ctx, getBankClientForUser, arg.ID, arg.UserID)
	var i GetBankClientForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.Label,
		&i.ProgramTierID,
		&i.BankName,
	)
	return i, err
}

const getCardForUser = `-- name: GetCardForUser :one
select bc.id, bc.last_4_digits, bc.payment_system, bc.image_filename, bc.bank_client_id, cl.bank_id, b.name as bank_name
from bank_card bc
         join bank_client cl on cl.id = bc.bank_client_id
         join bank b on b.id = cl.bank_id
where bc.id = $1
  and cl.user_id = $2
`

type GetCardForUserParams struct {
	ID     int32
	UserID uuid.UUID
}

type GetCardForUserRow struct {
	ID            int32
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ImageFilename *string
	BankClientID  int64
	BankID        int32
	BankName      string
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.ID, arg.UserID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.Last4Digits,
		&i.PaymentSystem,
		&i.ImageFilename,
		&i.BankClientID,
		&i.BankID,
		&i.BankName,
	)
	return i, err
}

const listBankClientsForUser = `-- name: ListBankClientsForUser :many
select cl.id, cl.user_id, cl.bank_id, cl.label, cl.program_tier_id, b.name as bank_name
from bank_client cl
         join bank b on b.id = cl.bank_id
where cl.user_id = $1
order by cl.id
`

type ListBankClientsForUserRow struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	Label         *string
	ProgramTierID *int64
	BankName      string
}

func (q *Queries) ListBankClientsForUser(ctx context.Context, userID uuid.UUID) ([]ListBankClientsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBankClientsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankClientsForUserRow
	for rows.Next() {
		var i ListBankClientsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BankID,
			&i.Label,
			&i.ProgramTierID,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBanks = `-- name: ListBanks :many
select id, name, logo_filename, color_hex
from bank
order by id
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.Query(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bank
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoFilename,
			&i.ColorHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForUser = `-- name: ListCardsForUser :many
select bc.id, bc.last_4_digits, bc.payment_system, bc.image_filename, bc.bank_client_id, cl.bank_id, b.name as bank_name
from bank_card bc
         join bank_client cl on cl.id = bc.bank_client_id
         join bank b on b.id = cl.bank_id
where cl.user_id = $1
order by bc.id
`

type ListCardsForUserRow struct {
	ID            int32
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ImageFilename *string
	BankClientID  int64
	BankID        int32
	BankName      string
}

func (q *Queries) ListCardsForUser(ctx context.Context, userID uuid.UUID) ([]ListCardsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsForUserRow
	for rows.Next() {
		var i ListCardsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Last4Digits,
			&i.PaymentSystem,
			&i.ImageFilename,
			&i.BankClientID,
			&i.BankID,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankClientForUser = `-- name: UpdateBankClientForUser :one
update bank_client
set label           = $3,
    program_tier_id = $4
where id = $1
  and user_id = $2
returning id, user_id, bank_id, label, program_tier_id
`

type UpdateBankClientForUserParams struct {
	ID            int64
	UserID        uuid.UUID
	Label         *string
	ProgramTierID *int64
}

func (q *Queries) UpdateBankClientForUser(ctx context.Context, arg UpdateBankClientForUserParams) (BankClient, error) {
	row := q.db.QueryRow(ctx, updateBankClientForUser,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.ProgramTierID,
	)
	var i BankClient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.Label,
		&i.ProgramTierID,
	)
	return i, err
}

const updateCardForUser = `-- name: UpdateCardForUser :one
update bank_card bc
set last_4_digits  = $3,
    payment_system = $4
from bank_client cl
where bc.id = $1
  and cl.id = bc.bank_client_id
  and cl.user_id = $2
returning bc.id, bc.last_4_digits, bc.payment_system, bc.image_filename, bc.bank_client_id
`

type UpdateCardForUserParams struct {
	ID            int32
	UserID        uuid.UUID
	Last4Digits   int32
	PaymentSystem PaymentSystem
}

func (q *Queries) UpdateCardForUser(ctx context.Context, arg UpdateCardForUserParams) (BankCard, error) {
	row := q.db.QueryRow(ctx, updateCardForUser,
		arg.ID,
		arg.UserID,
		arg.Last4Digits,
		arg.PaymentSystem,
	)
	var i BankCard
	err := row.Scan(
		&i.ID,
		&i.Last4Digits,
		&i.PaymentSystem,
		&i.ImageFilename,
		&i.BankClientID,
	)
	return i, err
}
