// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cashback.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const attachToOfferPeriod = `-- name: AttachToOfferPeriod :exec
insert into offer_period_attachment (offer_period_id, attachment_id)
values ($1, $2)
on conflict do nothing
`

type AttachToOfferPeriodParams struct {
	OfferPeriodID int64
	AttachmentID  uuid.UUID
}

func (q *Queries) AttachToOfferPeriod(ctx context.Context, arg AttachToOfferPeriodParams) error {
	_, err := q.db.Exec(ctx, attachToOfferPeriod, arg.OfferPeriodID, arg.AttachmentID)
	return err
}

const attachToPartnerOffer = `-- name: AttachToPartnerOffer :exec
insert into partner_offer_attachment (partner_offer_id, attachment_id)
values ($1, $2)
on conflict do nothing
`

type AttachToPartnerOfferParams struct {
	PartnerOfferID int64
	AttachmentID   uuid.UUID
}

func (q *Queries) AttachToPartnerOffer(ctx context.Context, arg AttachToPartnerOfferParams) error {
	_, err := q.db.Exec(ctx, attachToPartnerOffer, arg.PartnerOfferID, arg.AttachmentID)
	return err
}

const countRegularSelectionsInPeriod = `-- name: CountRegularSelectionsInPeriod :one
select count(*)
from selection s
         join category_offer co on co.id = s.category_offer_id
where co.offer_period_id = $1
  and co.kind = 'regular'
`

func (q *Queries) CountRegularSelectionsInPeriod(ctx context.Context, offerPeriodID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRegularSelectionsInPeriod, offerPeriodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankCategory = `-- name: CreateBankCategory :one
insert into bank_category (bank_id, title, canonical_category_id, kind, emoji, is_custom)
values ($1, $2, $3, $4, $5, true)
returning id, bank_id, title, canonical_category_id, kind, emoji, is_custom, active
`

type CreateBankCategoryParams struct {
	BankID              int32
	Title               string
	CanonicalCategoryID *int64
	Kind                CashbackOfferKind
	Emoji               *string
}

func (q *Queries) CreateBankCategory(ctx context.Context, arg CreateBankCategoryParams) (BankCategory, error) {
	row := q.db.QueryRow(ctx, createBankCategory,
		arg.BankID,
		arg.Title,
		arg.CanonicalCategoryID,
		arg.Kind,
		arg.Emoji,
	)
	var i BankCategory
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.CanonicalCategoryID,
		&i.Kind,
		&i.Emoji,
		&i.IsCustom,
		&i.Active,
	)
	return i, err
}

const createCanonicalCategory = `-- name: CreateCanonicalCategory :one
insert into canonical_category (slug, title_ru, emoji)
values ($1, $2, $3)
returning id, slug, title_ru, emoji
`

type CreateCanonicalCategoryParams struct {
	Slug    string
	TitleRu string
	Emoji   *string
}

func (q *Queries) CreateCanonicalCategory(ctx context.Context, arg CreateCanonicalCategoryParams) (CanonicalCategory, error) {
	row := q.db.QueryRow(ctx, createCanonicalCategory, arg.Slug, arg.TitleRu, arg.Emoji)
	var i CanonicalCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.Emoji,
	)
	return i, err
}

const createCategoryOffer = `-- name: CreateCategoryOffer :one
insert into category_offer (offer_period_id, raw_title, canonical_category_id, percent, kind, notes, bank_category_id, cap_value)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, offer_period_id, raw_title, canonical_category_id, percent, kind, notes, bank_category_id, cap_value
`

type CreateCategoryOfferParams struct {
	OfferPeriodID       int64
	RawTitle            string
	CanonicalCategoryID *int64
	Percent             *decimal.Decimal
	Kind                CashbackOfferKind
	Notes               *string
	BankCategoryID      *int64
	CapValue            *decimal.Decimal
}

func (q *Queries) CreateCategoryOffer(ctx context.Context, arg CreateCategoryOfferParams) (CategoryOffer, error) {
	row := q.db.QueryRow(ctx, createCategoryOffer,
		arg.OfferPeriodID,
		arg.RawTitle,
		arg.CanonicalCategoryID,
		arg.Percent,
		arg.Kind,
		arg.Notes,
		arg.BankCategoryID,
		arg.CapValue,
	)
	var i CategoryOffer
	err := row.Scan(
		&i.ID,
		&i.OfferPeriodID,
		&i.RawTitle,
		&i.CanonicalCategoryID,
		&i.Percent,
		&i.Kind,
		&i.Notes,
		&i.BankCategoryID,
		&i.CapValue,
	)
	return i, err
}

const createOfferPeriod = `-- name: CreateOfferPeriod :one
insert into offer_period (bank_client_id, period_start, period_end)
values ($1, $2, $3)
returning id, period_start, period_end, max_categories_override, bank_client_id
`

type CreateOfferPeriodParams struct {
	BankClientID int64
	PeriodStart  time.Time
	PeriodEnd    time.Time
}

func (q *Queries) CreateOfferPeriod(ctx context.Context, arg CreateOfferPeriodParams) (OfferPeriod, error) {
	row := q.db.QueryRow(ctx, createOfferPeriod, arg.BankClientID, arg.PeriodStart, arg.PeriodEnd)
	var i OfferPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MaxCategoriesOverride,
		&i.BankClientID,
	)
	return i, err
}

const createPartnerOffer = `-- name: CreatePartnerOffer :one
insert into partner_offer (user_id, bank_id, bank_client_id, merchant_title, percent,
                           valid_from, valid_to, cap_value, notes, min_amount)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, user_id, bank_id, merchant_title, percent, valid_from, valid_to, cap_value, notes, bank_client_id, min_amount
`

type CreatePartnerOfferParams struct {
	UserID        uuid.UUID
	BankID        int32
	BankClientID  *int64
	MerchantTitle string
	Percent       *decimal.Decimal
	ValidFrom     *time.Time
	ValidTo       *time.Time
	CapValue      *decimal.Decimal
	Notes         *string
	MinAmount     *decimal.Decimal
}

func (q *Queries) CreatePartnerOffer(ctx context.Context, arg CreatePartnerOfferParams) (PartnerOffer, error) {
	row := q.db.QueryRow(ctx, createPartnerOffer,
		arg.UserID,
		arg.BankID,
		arg.BankClientID,
		arg.MerchantTitle,
		arg.Percent,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CapValue,
		arg.Notes,
		arg.MinAmount,
	)
	var i PartnerOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.MerchantTitle,
		&i.Percent,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CapValue,
		&i.Notes,
		&i.BankClientID,
		&i.MinAmount,
	)
	return i, err
}

const createSelection = `-- name: CreateSelection :one
insert into selection (category_offer_id, selected_at)
values ($1, $2)
returning id, category_offer_id, selected_at
`

type CreateSelectionParams struct {
	CategoryOfferID int64
	SelectedAt      time.Time
}

func (q *Queries) CreateSelection(ctx context.Context, arg CreateSelectionParams) (Selection, error) {
	row := q.db.QueryRow(ctx, createSelection, arg.CategoryOfferID, arg.SelectedAt)
	var i Selection
	err := row.Scan(&i.ID, &i.CategoryOfferID, &i.SelectedAt)
	return i, err
}

const deleteAttachmentIfOrphan = `-- name: DeleteAttachmentIfOrphan :execrows
delete
from attachment a
where a.id = $1
  and a.user_id = $2
  and not exists (select 1 from offer_period_attachment where attachment_id = $1)
  and not exists (select 1 from partner_offer_attachment where attachment_id = $1)
`

type DeleteAttachmentIfOrphanParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

// DeleteAttachmentIfOrphan removes the attachment row once nothing links
// to it (period or partner joins); the caller then removes the disk file.
func (q *Queries) DeleteAttachmentIfOrphan(ctx context.Context, arg DeleteAttachmentIfOrphanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachmentIfOrphan, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCategoryOffer = `-- name: DeleteCategoryOffer :exec
delete
from category_offer
where id = $1
`

func (q *Queries) DeleteCategoryOffer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategoryOffer, id)
	return err
}

const deleteOfferPeriod = `-- name: DeleteOfferPeriod :exec
delete
from offer_period
where id = $1
`

func (q *Queries) DeleteOfferPeriod(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOfferPeriod, id)
	return err
}

const deleteOfferPeriodAttachments = `-- name: DeleteOfferPeriodAttachments :exec
delete
from offer_period_attachment
where offer_period_id = $1
`

func (q *Queries) DeleteOfferPeriodAttachments(ctx context.Context, offerPeriodID int64) error {
	_, err := q.db.Exec(ctx, deleteOfferPeriodAttachments, offerPeriodID)
	return err
}

const deletePartnerOfferForUser = `-- name: DeletePartnerOfferForUser :execrows
delete
from partner_offer
where id = $1
  and user_id = $2
`

type DeletePartnerOfferForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeletePartnerOfferForUser(ctx context.Context, arg DeletePartnerOfferForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePartnerOfferForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgram = `-- name: DeleteProgram :execrows
delete
from cashback_program
where id = $1
`

func (q *Queries) DeleteProgram(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgram, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSelectionByOffer = `-- name: DeleteSelectionByOffer :exec
delete
from selection
where category_offer_id = $1
`

func (q *Queries) DeleteSelectionByOffer(ctx context.Context, categoryOfferID int64) error {
	_, err := q.db.Exec(ctx, deleteSelectionByOffer, categoryOfferID)
	return err
}

const deleteSelectionForUser = `-- name: DeleteSelectionForUser :execrows
delete
from selection s
    using category_offer co, offer_period op, bank_client cl
where s.id = $1
  and co.id = s.category_offer_id
  and op.id = co.offer_period_id
  and cl.id = op.bank_client_id
  and cl.user_id = $2
`

type DeleteSelectionForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeleteSelectionForUser(ctx context.Context, arg DeleteSelectionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSelectionForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTier = `-- name: DeleteTier :execrows
delete
from program_tier
where id = $1
`

func (q *Queries) DeleteTier(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTier, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachFromOfferPeriod = `-- name: DetachFromOfferPeriod :execrows
delete
from offer_period_attachment
where offer_period_id = $1
  and attachment_id = $2
`

type DetachFromOfferPeriodParams struct {
	OfferPeriodID int64
	AttachmentID  uuid.UUID
}

func (q *Queries) DetachFromOfferPeriod(ctx context.Context, arg DetachFromOfferPeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachFromOfferPeriod, arg.OfferPeriodID, arg.AttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachFromPartnerOffer = `-- name: DetachFromPartnerOffer :execrows
delete
from partner_offer_attachment
where partner_offer_id = $1
  and attachment_id = $2
`

type DetachFromPartnerOfferParams struct {
	PartnerOfferID int64
	AttachmentID   uuid.UUID
}

func (q *Queries) DetachFromPartnerOffer(ctx context.Context, arg DetachFromPartnerOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachFromPartnerOffer, arg.PartnerOfferID, arg.AttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBankCategory = `-- name: GetBankCategory :one
select id, bank_id, title, canonical_category_id, kind, emoji, is_custom, active
from bank_category
where id = $1
`

func (q *Queries) GetBankCategory(ctx context.Context, id int64) (BankCategory, error) {
	row := q.db.QueryRow(ctx, getBankCategory, id)
	var i BankCategory
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.CanonicalCategoryID,
		&i.Kind,
		&i.Emoji,
		&i.IsCustom,
		&i.Active,
	)
	return i, err
}

const getCanonicalCategoryBySlug = `-- name: GetCanonicalCategoryBySlug :one
select id, slug, title_ru, emoji
from canonical_category
where slug = $1
`

func (q *Queries) GetCanonicalCategoryBySlug(ctx context.Context, slug string) (CanonicalCategory, error) {
	row := q.db.QueryRow(ctx, getCanonicalCategoryBySlug, slug)
	var i CanonicalCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.Emoji,
	)
	return i, err
}

const getOfferPeriodForUser = `-- name: GetOfferPeriodForUser :one
select op.id, op.period_start, op.period_end, op.max_categories_override, op.bank_client_id, cl.bank_id, cl.label as holder_label, cl.program_tier_id, b.name as bank_name
from offer_period op
         join bank_client cl on cl.id = op.bank_client_id
         join bank b on b.id = cl.bank_id
where op.id = $1
  and cl.user_id = $2
`

type GetOfferPeriodForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetOfferPeriodForUserRow struct {
	ID                    int64
	PeriodStart           time.Time
	PeriodEnd             time.Time
	MaxCategoriesOverride *int32
	BankClientID          int64
	BankID                int32
	HolderLabel           *string
	ProgramTierID         *int64
	BankName              string
}

func (q *Queries) GetOfferPeriodForUser(ctx context.Context, arg GetOfferPeriodForUserParams) (GetOfferPeriodForUserRow, error) {
	row := q.db.QueryRow(ctx, getOfferPeriodForUser, arg.ID, arg.UserID)
	var i GetOfferPeriodForUserRow
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MaxCategoriesOverride,
		&i.BankClientID,
		&i.BankID,
		&i.HolderLabel,
		&i.ProgramTierID,
		&i.BankName,
	)
	return i, err
}

const getOfferWithContextForUser = `-- name: GetOfferWithContextForUser :one
select co.id, co.offer_period_id, co.raw_title, co.canonical_category_id, co.percent, co.kind, co.notes, co.bank_category_id, co.cap_value,
       op.bank_client_id,
       op.period_start,
       op.period_end,
       op.max_categories_override,
       cl.bank_id,
       cl.program_tier_id,
       (s.id is not null)::bool as already_selected
from category_offer co
         join offer_period op on op.id = co.offer_period_id
         join bank_client cl on cl.id = op.bank_client_id
         left join selection s on s.category_offer_id = co.id
where co.id = $1
  and cl.user_id = $2
`

type GetOfferWithContextForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetOfferWithContextForUserRow struct {
	ID                    int64
	OfferPeriodID         int64
	RawTitle              string
	CanonicalCategoryID   *int64
	Percent               *decimal.Decimal
	Kind                  CashbackOfferKind
	Notes                 *string
	BankCategoryID        *int64
	CapValue              *decimal.Decimal
	BankClientID          int64
	PeriodStart           time.Time
	PeriodEnd             time.Time
	MaxCategoriesOverride *int32
	BankID                int32
	ProgramTierID         *int64
	AlreadySelected       bool
}

func (q *Queries) GetOfferWithContextForUser(ctx context.Context, arg GetOfferWithContextForUserParams) (GetOfferWithContextForUserRow, error) {
	row := q.db.QueryRow(ctx, getOfferWithContextForUser, arg.ID, arg.UserID)
	var i GetOfferWithContextForUserRow
	err := row.Scan(
		&i.ID,
		&i.OfferPeriodID,
		&i.RawTitle,
		&i.CanonicalCategoryID,
		&i.Percent,
		&i.Kind,
		&i.Notes,
		&i.BankCategoryID,
		&i.CapValue,
		&i.BankClientID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MaxCategoriesOverride,
		&i.BankID,
		&i.ProgramTierID,
		&i.AlreadySelected,
	)
	return i, err
}

const getPartnerOfferForUser = `-- name: GetPartnerOfferForUser :one
select po.id, po.user_id, po.bank_id, po.merchant_title, po.percent, po.valid_from, po.valid_to, po.cap_value, po.notes, po.bank_client_id, po.min_amount, b.name as bank_name
from partner_offer po
         join bank b on b.id = po.bank_id
where po.id = $1
  and po.user_id = $2
`

type GetPartnerOfferForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetPartnerOfferForUserRow struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	MerchantTitle string
	Percent       *decimal.Decimal
	ValidFrom     *time.Time
	ValidTo       *time.Time
	CapValue      *decimal.Decimal
	Notes         *string
	BankClientID  *int64
	MinAmount     *decimal.Decimal
	BankName      string
}

func (q *Queries) GetPartnerOfferForUser(ctx context.Context, arg GetPartnerOfferForUserParams) (GetPartnerOfferForUserRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOfferForUser, arg.ID, arg.UserID)
	var i GetPartnerOfferForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.MerchantTitle,
		&i.Percent,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CapValue,
		&i.Notes,
		&i.BankClientID,
		&i.MinAmount,
		&i.BankName,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
select id, bank_id, name, period_type, selection_mode, currency_kind, points_label, selection_opens_day, notes, mid_period_add, activation
from cashback_program
where id = $1
`

func (q *Queries) GetProgram(ctx context.Context, id int64) (CashbackProgram, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i CashbackProgram
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Name,
		&i.PeriodType,
		&i.SelectionMode,
		&i.CurrencyKind,
		&i.PointsLabel,
		&i.SelectionOpensDay,
		&i.Notes,
		&i.MidPeriodAdd,
		&i.Activation,
	)
	return i, err
}

const getTier = `-- name: GetTier :one
select id, program_id, name, is_paid_subscription, cap_value, cap_scope, cap_per_category, max_categories, notes
from program_tier
where id = $1
`

func (q *Queries) GetTier(ctx context.Context, id int64) (ProgramTier, error) {
	row := q.db.QueryRow(ctx, getTier, id)
	var i ProgramTier
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Name,
		&i.IsPaidSubscription,
		&i.CapValue,
		&i.CapScope,
		&i.CapPerCategory,
		&i.MaxCategories,
		&i.Notes,
	)
	return i, err
}

const listAliasesForBank = `-- name: ListAliasesForBank :many
select canonical_category_id, bank_id, raw_title
from bank_category_alias
where bank_id = $1
`

func (q *Queries) ListAliasesForBank(ctx context.Context, bankID int32) ([]BankCategoryAlias, error) {
	rows, err := q.db.Query(ctx, listAliasesForBank, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankCategoryAlias
	for rows.Next() {
		var i BankCategoryAlias
		if err := rows.Scan(&i.CanonicalCategoryID, &i.BankID, &i.RawTitle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankCategories = `-- name: ListBankCategories :many
select bc.id, bc.bank_id, bc.title, bc.canonical_category_id, bc.kind, bc.emoji, bc.is_custom, bc.active,
       cc.slug     as canonical_slug,
       cc.title_ru as canonical_title_ru,
       cc.emoji    as canonical_emoji
from bank_category bc
         left join canonical_category cc on cc.id = bc.canonical_category_id
where bc.bank_id = $1
  and bc.active
order by bc.kind, bc.title
`

type ListBankCategoriesRow struct {
	ID                  int64
	BankID              int32
	Title               string
	CanonicalCategoryID *int64
	Kind                CashbackOfferKind
	Emoji               *string
	IsCustom            bool
	Active              bool
	CanonicalSlug       *string
	CanonicalTitleRu    *string
	CanonicalEmoji      *string
}

func (q *Queries) ListBankCategories(ctx context.Context, bankID int32) ([]ListBankCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listBankCategories, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankCategoriesRow
	for rows.Next() {
		var i ListBankCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.Title,
			&i.CanonicalCategoryID,
			&i.Kind,
			&i.Emoji,
			&i.IsCustom,
			&i.Active,
			&i.CanonicalSlug,
			&i.CanonicalTitleRu,
			&i.CanonicalEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanonicalCategories = `-- name: ListCanonicalCategories :many
select id, slug, title_ru, emoji
from canonical_category
order by slug
`

func (q *Queries) ListCanonicalCategories(ctx context.Context) ([]CanonicalCategory, error) {
	rows, err := q.db.Query(ctx, listCanonicalCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CanonicalCategory
	for rows.Next() {
		var i CanonicalCategory
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleRu,
			&i.Emoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferIDsForPeriod = `-- name: ListOfferIDsForPeriod :many
select id
from category_offer
where offer_period_id = $1
`

func (q *Queries) ListOfferIDsForPeriod(ctx context.Context, offerPeriodID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOfferIDsForPeriod, offerPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferPeriodAttachments = `-- name: ListOfferPeriodAttachments :many
select a.id, a.filename, a.media_type, a.user_id
from attachment a
         join offer_period_attachment opa on opa.attachment_id = a.id
where opa.offer_period_id = $1
`

func (q *Queries) ListOfferPeriodAttachments(ctx context.Context, offerPeriodID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listOfferPeriodAttachments, offerPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MediaType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferPeriodsForUser = `-- name: ListOfferPeriodsForUser :many
select op.id, op.period_start, op.period_end, op.max_categories_override, op.bank_client_id, cl.bank_id, cl.label as holder_label, b.name as bank_name
from offer_period op
         join bank_client cl on cl.id = op.bank_client_id
         join bank b on b.id = cl.bank_id
where cl.user_id = $1
order by op.period_start desc, op.id
`

type ListOfferPeriodsForUserRow struct {
	ID                    int64
	PeriodStart           time.Time
	PeriodEnd             time.Time
	MaxCategoriesOverride *int32
	BankClientID          int64
	BankID                int32
	HolderLabel           *string
	BankName              string
}

func (q *Queries) ListOfferPeriodsForUser(ctx context.Context, userID uuid.UUID) ([]ListOfferPeriodsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOfferPeriodsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfferPeriodsForUserRow
	for rows.Next() {
		var i ListOfferPeriodsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.MaxCategoriesOverride,
			&i.BankClientID,
			&i.BankID,
			&i.HolderLabel,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersForClients = `-- name: ListOffersForClients :many
select co.id                     as category_offer_id,
       co.raw_title,
       co.canonical_category_id,
       co.percent,
       co.kind,
       co.cap_value              as offer_cap_value,
       op.id                     as offer_period_id,
       op.bank_client_id,
       op.period_start,
       op.period_end,
       op.max_categories_override,
       cl.label                  as holder_label,
       b.name                    as bank_name,
       pt.cap_value,
       pt.cap_scope              as tier_cap_scope,
       pt.cap_per_category,
       pt.max_categories,
       cp.currency_kind          as program_currency_kind,
       cp.points_label,
       coalesce((select cpb.mid_period_add
                 from cashback_program cpb
                 where cpb.bank_id = cl.bank_id
                 limit 1), 'unknown')::cashback_mid_period_add as mid_period_add,
       coalesce((select cpb.activation
                 from cashback_program cpb
                 where cpb.bank_id = cl.bank_id
                 limit 1), 'unknown')::cashback_activation     as activation,
       (s.id is not null)::bool  as selected,
       s.selected_at
from category_offer co
         join offer_period op on op.id = co.offer_period_id
         join bank_client cl on cl.id = op.bank_client_id
         join bank b on b.id = cl.bank_id
         left join selection s on s.category_offer_id = co.id
         left join program_tier pt on pt.id = cl.program_tier_id
         left join cashback_program cp on cp.id = pt.program_id
where op.bank_client_id = any ($1::bigint[])
`

type ListOffersForClientsRow struct {
	CategoryOfferID       int64
	RawTitle              string
	CanonicalCategoryID   *int64
	Percent               *decimal.Decimal
	Kind                  CashbackOfferKind
	OfferCapValue         *decimal.Decimal
	OfferPeriodID         int64
	BankClientID          int64
	PeriodStart           time.Time
	PeriodEnd             time.Time
	MaxCategoriesOverride *int32
	HolderLabel           *string
	BankName              string
	CapValue              *decimal.Decimal
	TierCapScope          NullCashbackCapScope
	CapPerCategory        *decimal.Decimal
	MaxCategories         *int32
	ProgramCurrencyKind   NullCashbackCurrencyKind
	PointsLabel           *string
	MidPeriodAdd          CashbackMidPeriodAdd
	Activation            CashbackActivation
	Selected              bool
	SelectedAt            *time.Time
}

// ListOffersForClients is ListUserOffers keyed by explicit client ids
// instead of the owner — the friends-sharing read path
// (docs/specs/friends-sharing.md). The row shape is kept identical on
// purpose: entryOf and the period filters reuse verbatim. The caller is
// responsible for passing only GRANTED client ids (the friends module
// resolves them); this module stays the only reader of cashback tables.
func (q *Queries) ListOffersForClients(ctx context.Context, clientIds []int64) ([]ListOffersForClientsRow, error) {
	rows, err := q.db.Query(ctx, listOffersForClients, clientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersForClientsRow
	for rows.Next() {
		var i ListOffersForClientsRow
		if err := rows.Scan(
			&i.CategoryOfferID,
			&i.RawTitle,
			&i.CanonicalCategoryID,
			&i.Percent,
			&i.Kind,
			&i.OfferCapValue,
			&i.OfferPeriodID,
			&i.BankClientID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.MaxCategoriesOverride,
			&i.HolderLabel,
			&i.BankName,
			&i.CapValue,
			&i.TierCapScope,
			&i.CapPerCategory,
			&i.MaxCategories,
			&i.ProgramCurrencyKind,
			&i.PointsLabel,
			&i.MidPeriodAdd,
			&i.Activation,
			&i.Selected,
			&i.SelectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersForPeriod = `-- name: ListOffersForPeriod :many
select co.id, co.offer_period_id, co.raw_title, co.canonical_category_id, co.percent, co.kind, co.notes, co.bank_category_id, co.cap_value, s.id as selection_id, s.selected_at
from category_offer co
         left join selection s on s.category_offer_id = co.id
where co.offer_period_id = $1
order by co.id
`

type ListOffersForPeriodRow struct {
	ID                  int64
	OfferPeriodID       int64
	RawTitle            string
	CanonicalCategoryID *int64
	Percent             *decimal.Decimal
	Kind                CashbackOfferKind
	Notes               *string
	BankCategoryID      *int64
	CapValue            *decimal.Decimal
	SelectionID         *int64
	SelectedAt          *time.Time
}

func (q *Queries) ListOffersForPeriod(ctx context.Context, offerPeriodID int64) ([]ListOffersForPeriodRow, error) {
	rows, err := q.db.Query(ctx, listOffersForPeriod, offerPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersForPeriodRow
	for rows.Next() {
		var i ListOffersForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.OfferPeriodID,
			&i.RawTitle,
			&i.CanonicalCategoryID,
			&i.Percent,
			&i.Kind,
			&i.Notes,
			&i.BankCategoryID,
			&i.CapValue,
			&i.SelectionID,
			&i.SelectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerOfferAttachments = `-- name: ListPartnerOfferAttachments :many
select a.id, a.filename, a.media_type, a.user_id
from attachment a
         join partner_offer_attachment poa on poa.attachment_id = a.id
where poa.partner_offer_id = $1
`

func (q *Queries) ListPartnerOfferAttachments(ctx context.Context, partnerOfferID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listPartnerOfferAttachments, partnerOfferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MediaType,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerOffersForUser = `-- name: ListPartnerOffersForUser :many
select po.id, po.user_id, po.bank_id, po.merchant_title, po.percent, po.valid_from, po.valid_to, po.cap_value, po.notes, po.bank_client_id, po.min_amount, b.name as bank_name
from partner_offer po
         join bank b on b.id = po.bank_id
where po.user_id = $1
order by po.id
`

type ListPartnerOffersForUserRow struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	MerchantTitle string
	Percent       *decimal.Decimal
	ValidFrom     *time.Time
	ValidTo       *time.Time
	CapValue      *decimal.Decimal
	Notes         *string
	BankClientID  *int64
	MinAmount     *decimal.Decimal
	BankName      string
}

func (q *Queries) ListPartnerOffersForUser(ctx context.Context, userID uuid.UUID) ([]ListPartnerOffersForUserRow, error) {
	rows, err := q.db.Query(ctx, listPartnerOffersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerOffersForUserRow
	for rows.Next() {
		var i ListPartnerOffersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BankID,
			&i.MerchantTitle,
			&i.Percent,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CapValue,
			&i.Notes,
			&i.BankClientID,
			&i.MinAmount,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodRangesForClient = `-- name: ListPeriodRangesForClient :many
select period_start, period_end
from offer_period
where bank_client_id = $1
`

type ListPeriodRangesForClientRow struct {
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) ListPeriodRangesForClient(ctx context.Context, bankClientID int64) ([]ListPeriodRangesForClientRow, error) {
	rows, err := q.db.Query(ctx, listPeriodRangesForClient, bankClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeriodRangesForClientRow
	for rows.Next() {
		var i ListPeriodRangesForClientRow
		if err := rows.Scan(&i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many

select cp.id, cp.bank_id, cp.name, cp.period_type, cp.selection_mode, cp.currency_kind, cp.points_label, cp.selection_opens_day, cp.notes, cp.mid_period_add, cp.activation, b.name as bank_name
from cashback_program cp
         join bank b on b.id = cp.bank_id
order by cp.id
`

type ListProgramsRow struct {
	ID                int64
	BankID            int32
	Name              string
	PeriodType        CashbackPeriodType
	SelectionMode     CashbackSelectionMode
	CurrencyKind      CashbackCurrencyKind
	PointsLabel       *string
	SelectionOpensDay *int32
	Notes             *string
	MidPeriodAdd      CashbackMidPeriodAdd
	Activation        CashbackActivation
	BankName          string
}

// Cashback module queries. Seam note: joins to bank / bank_client are the
// module's read-only reference reads (decided at skeleton, see
// 00003_cashback.sql header; re-keyed card→client in 00006); no other
// module touches cashback tables.
func (q *Queries) ListPrograms(ctx context.Context) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramsRow
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.Name,
			&i.PeriodType,
			&i.SelectionMode,
			&i.CurrencyKind,
			&i.PointsLabel,
			&i.SelectionOpensDay,
			&i.Notes,
			&i.MidPeriodAdd,
			&i.Activation,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiersForProgram = `-- name: ListTiersForProgram :many
select id, program_id, name, is_paid_subscription, cap_value, cap_scope, cap_per_category, max_categories, notes
from program_tier
where program_id = $1
order by id
`

func (q *Queries) ListTiersForProgram(ctx context.Context, programID int64) ([]ProgramTier, error) {
	rows, err := q.db.Query(ctx, listTiersForProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramTier
	for rows.Next() {
		var i ProgramTier
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Name,
			&i.IsPaidSubscription,
			&i.CapValue,
			&i.CapScope,
			&i.CapPerCategory,
			&i.MaxCategories,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOffers = `-- name: ListUserOffers :many
select co.id                     as category_offer_id,
       co.raw_title,
       co.canonical_category_id,
       co.percent,
       co.kind,
       co.cap_value              as offer_cap_value,
       op.id                     as offer_period_id,
       op.bank_client_id,
       op.period_start,
       op.period_end,
       op.max_categories_override,
       cl.label                  as holder_label,
       b.name                    as bank_name,
       pt.cap_value,
       pt.cap_scope              as tier_cap_scope,
       pt.cap_per_category,
       pt.max_categories,
       cp.currency_kind          as program_currency_kind,
       cp.points_label,
       -- Program-level policy reached via the BANK, not the tier: a client
       -- without a tier still falls under the bank's program (S3b verdicts
       -- must not degrade to 'unknown' just because no tier is set).
       -- coalesce: banks without a seeded program (Сбербанк/Т-Банк) → unknown.
       coalesce((select cpb.mid_period_add
                 from cashback_program cpb
                 where cpb.bank_id = cl.bank_id
                 limit 1), 'unknown')::cashback_mid_period_add as mid_period_add,
       coalesce((select cpb.activation
                 from cashback_program cpb
                 where cpb.bank_id = cl.bank_id
                 limit 1), 'unknown')::cashback_activation     as activation,
       (s.id is not null)::bool  as selected,
       s.selected_at
from category_offer co
         join offer_period op on op.id = co.offer_period_id
         join bank_client cl on cl.id = op.bank_client_id
         join bank b on b.id = cl.bank_id
         left join selection s on s.category_offer_id = co.id
         left join program_tier pt on pt.id = cl.program_tier_id
         left join cashback_program cp on cp.id = pt.program_id
where cl.user_id = $1
`

type ListUserOffersRow struct {
	CategoryOfferID       int64
	RawTitle              string
	CanonicalCategoryID   *int64
	Percent               *decimal.Decimal
	Kind                  CashbackOfferKind
	OfferCapValue         *decimal.Decimal
	OfferPeriodID         int64
	BankClientID          int64
	PeriodStart           time.Time
	PeriodEnd             time.Time
	MaxCategoriesOverride *int32
	HolderLabel           *string
	BankName              string
	CapValue              *decimal.Decimal
	TierCapScope          NullCashbackCapScope
	CapPerCategory        *decimal.Decimal
	MaxCategories         *int32
	ProgramCurrencyKind   NullCashbackCurrencyKind
	PointsLabel           *string
	MidPeriodAdd          CashbackMidPeriodAdd
	Activation            CashbackActivation
	Selected              bool
	SelectedAt            *time.Time
}

// ListUserOffers is the helper/lookup workhorse: every menu row of the
// user's bank clients with its period, client, tier-cap and program-currency
// context, plus whether it is selected. Filtering (overlap, currency, kind,
// date) is domain logic in Go — data volume is personal-app sized.
func (q *Queries) ListUserOffers(ctx context.Context, userID uuid.UUID) ([]ListUserOffersRow, error) {
	rows, err := q.db.Query(ctx, listUserOffers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOffersRow
	for rows.Next() {
		var i ListUserOffersRow
		if err := rows.Scan(
			&i.CategoryOfferID,
			&i.RawTitle,
			&i.CanonicalCategoryID,
			&i.Percent,
			&i.Kind,
			&i.OfferCapValue,
			&i.OfferPeriodID,
			&i.BankClientID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.MaxCategoriesOverride,
			&i.HolderLabel,
			&i.BankName,
			&i.CapValue,
			&i.TierCapScope,
			&i.CapPerCategory,
			&i.MaxCategories,
			&i.ProgramCurrencyKind,
			&i.PointsLabel,
			&i.MidPeriodAdd,
			&i.Activation,
			&i.Selected,
			&i.SelectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOfferPeriodMaxOverride = `-- name: SetOfferPeriodMaxOverride :one
update offer_period op
set max_categories_override = $3
from bank_client cl
where op.id = $1
  and cl.id = op.bank_client_id
  and cl.user_id = $2
returning op.id, op.period_start, op.period_end, op.max_categories_override, op.bank_client_id
`

type SetOfferPeriodMaxOverrideParams struct {
	ID                    int64
	UserID                uuid.UUID
	MaxCategoriesOverride *int32
}

func (q *Queries) SetOfferPeriodMaxOverride(ctx context.Context, arg SetOfferPeriodMaxOverrideParams) (OfferPeriod, error) {
	row := q.db.QueryRow(ctx, setOfferPeriodMaxOverride, arg.ID, arg.UserID, arg.MaxCategoriesOverride)
	var i OfferPeriod
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MaxCategoriesOverride,
		&i.BankClientID,
	)
	return i, err
}

const updateCategoryOfferForUser = `-- name: UpdateCategoryOfferForUser :one
update category_offer co
set raw_title             = $3,
    canonical_category_id = $4,
    percent               = $5,
    kind                  = $6,
    notes                 = $7,
    bank_category_id      = $8,
    cap_value             = $9
from offer_period op,
     bank_client cl
where co.id = $1
  and op.id = co.offer_period_id
  and cl.id = op.bank_client_id
  and cl.user_id = $2
returning co.id, co.offer_period_id, co.raw_title, co.canonical_category_id, co.percent, co.kind, co.notes, co.bank_category_id, co.cap_value
`

type UpdateCategoryOfferForUserParams struct {
	ID                  int64
	UserID              uuid.UUID
	RawTitle            string
	CanonicalCategoryID *int64
	Percent             *decimal.Decimal
	Kind                CashbackOfferKind
	Notes               *string
	BankCategoryID      *int64
	CapValue            *decimal.Decimal
}

func (q *Queries) UpdateCategoryOfferForUser(ctx context.Context, arg UpdateCategoryOfferForUserParams) (CategoryOffer, error) {
	row := q.db.QueryRow(ctx, updateCategoryOfferForUser,
		arg.ID,
		arg.UserID,
		arg.RawTitle,
		arg.CanonicalCategoryID,
		arg.Percent,
		arg.Kind,
		arg.Notes,
		arg.BankCategoryID,
		arg.CapValue,
	)
	var i CategoryOffer
	err := row.Scan(
		&i.ID,
		&i.OfferPeriodID,
		&i.RawTitle,
		&i.CanonicalCategoryID,
		&i.Percent,
		&i.Kind,
		&i.Notes,
		&i.BankCategoryID,
		&i.CapValue,
	)
	return i, err
}

const updatePartnerOfferForUser = `-- name: UpdatePartnerOfferForUser :one
update partner_offer
set bank_id        = $3,
    bank_client_id = $4,
    merchant_title = $5,
    percent        = $6,
    valid_from     = $7,
    valid_to       = $8,
    cap_value      = $9,
    notes          = $10,
    min_amount     = $11
where id = $1
  and user_id = $2
returning id, user_id, bank_id, merchant_title, percent, valid_from, valid_to, cap_value, notes, bank_client_id, min_amount
`

type UpdatePartnerOfferForUserParams struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	BankClientID  *int64
	MerchantTitle string
	Percent       *decimal.Decimal
	ValidFrom     *time.Time
	ValidTo       *time.Time
	CapValue      *decimal.Decimal
	Notes         *string
	MinAmount     *decimal.Decimal
}

func (q *Queries) UpdatePartnerOfferForUser(ctx context.Context, arg UpdatePartnerOfferForUserParams) (PartnerOffer, error) {
	row := q.db.QueryRow(ctx, updatePartnerOfferForUser,
		arg.ID,
		arg.UserID,
		arg.BankID,
		arg.BankClientID,
		arg.MerchantTitle,
		arg.Percent,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CapValue,
		arg.Notes,
		arg.MinAmount,
	)
	var i PartnerOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankID,
		&i.MerchantTitle,
		&i.Percent,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CapValue,
		&i.Notes,
		&i.BankClientID,
		&i.MinAmount,
	)
	return i, err
}

const updateProgram = `-- name: UpdateProgram :one
update cashback_program
set name                = $2,
    period_type         = $3,
    selection_mode      = $4,
    currency_kind       = $5,
    points_label        = $6,
    selection_opens_day = $7,
    notes               = $8
where id = $1
returning id, bank_id, name, period_type, selection_mode, currency_kind, points_label, selection_opens_day, notes, mid_period_add, activation
`

type UpdateProgramParams struct {
	ID                int64
	Name              string
	PeriodType        CashbackPeriodType
	SelectionMode     CashbackSelectionMode
	CurrencyKind      CashbackCurrencyKind
	PointsLabel       *string
	SelectionOpensDay *int32
	Notes             *string
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (CashbackProgram, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.Name,
		arg.PeriodType,
		arg.SelectionMode,
		arg.CurrencyKind,
		arg.PointsLabel,
		arg.SelectionOpensDay,
		arg.Notes,
	)
	var i CashbackProgram
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Name,
		&i.PeriodType,
		&i.SelectionMode,
		&i.CurrencyKind,
		&i.PointsLabel,
		&i.SelectionOpensDay,
		&i.Notes,
		&i.MidPeriodAdd,
		&i.Activation,
	)
	return i, err
}

const updateTier = `-- name: UpdateTier :one
update program_tier
set name                 = $2,
    is_paid_subscription = $3,
    cap_value            = $4,
    cap_scope            = $5,
    cap_per_category     = $6,
    max_categories       = $7,
    notes                = $8
where id = $1
returning id, program_id, name, is_paid_subscription, cap_value, cap_scope, cap_per_category, max_categories, notes
`

type UpdateTierParams struct {
	ID                 int64
	Name               string
	IsPaidSubscription bool
	CapValue           *decimal.Decimal
	CapScope           CashbackCapScope
	CapPerCategory     *decimal.Decimal
	MaxCategories      *int32
	Notes              *string
}

func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) (ProgramTier, error) {
	row := q.db.QueryRow(ctx, updateTier,
		arg.ID,
		arg.Name,
		arg.IsPaidSubscription,
		arg.CapValue,
		arg.CapScope,
		arg.CapPerCategory,
		arg.MaxCategories,
		arg.Notes,
	)
	var i ProgramTier
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Name,
		&i.IsPaidSubscription,
		&i.CapValue,
		&i.CapScope,
		&i.CapPerCategory,
		&i.MaxCategories,
		&i.Notes,
	)
	return i, err
}

const upsertAlias = `-- name: UpsertAlias :exec
insert into bank_category_alias (canonical_category_id, bank_id, raw_title)
values ($1, $2, $3)
on conflict (bank_id, raw_title) do update set canonical_category_id = excluded.canonical_category_id
`

type UpsertAliasParams struct {
	CanonicalCategoryID int64
	BankID              int32
	RawTitle            string
}

func (q *Queries) UpsertAlias(ctx context.Context, arg UpsertAliasParams) error {
	_, err := q.db.Exec(ctx, upsertAlias, arg.CanonicalCategoryID, arg.BankID, arg.RawTitle)
	return err
}
