// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelRequestForSender = `-- name: CancelRequestForSender :execrows
update friend_request
set status       = 'cancelled',
    responded_at = now()
where id = $1
  and from_user_id = $2
  and status = 'pending'
`

type CancelRequestForSenderParams struct {
	ID         int64
	FromUserID uuid.UUID
}

func (q *Queries) CancelRequestForSender(ctx context.Context, arg CancelRequestForSenderParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRequestForSender, arg.ID, arg.FromUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimInvite = `-- name: ClaimInvite :one
update friend_invite
set claimed_at         = now(),
    claimed_by_user_id = $2
where token_hash = $1
  and claimed_at is null
  and expires_at > now()
returning id, created_by_user_id, token_hash, created_at, expires_at, claimed_at, claimed_by_user_id
`

type ClaimInviteParams struct {
	TokenHash       []byte
	ClaimedByUserID *uuid.UUID
}

// ClaimInvite is the atomic burn (invariant 5): the conditional update
// either claims a live, unexpired invite or matches nothing — the service
// distinguishes burned from expired via GetInviteByTokenHash afterwards.
func (q *Queries) ClaimInvite(ctx context.Context, arg ClaimInviteParams) (FriendInvite, error) {
	row := q.db.QueryRow(ctx, claimInvite, arg.TokenHash, arg.ClaimedByUserID)
	var i FriendInvite
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
	)
	return i, err
}

const createFriendInvite = `-- name: CreateFriendInvite :one
insert into friend_invite (created_by_user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, created_by_user_id, token_hash, created_at, expires_at, claimed_at, claimed_by_user_id
`

type CreateFriendInviteParams struct {
	CreatedByUserID uuid.UUID
	TokenHash       []byte
	ExpiresAt       time.Time
}

func (q *Queries) CreateFriendInvite(ctx context.Context, arg CreateFriendInviteParams) (FriendInvite, error) {
	row := q.db.QueryRow(ctx, createFriendInvite, arg.CreatedByUserID, arg.TokenHash, arg.ExpiresAt)
	var i FriendInvite
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
insert into friend_request (from_user_id, to_user_id)
values ($1, $2)
returning id, from_user_id, to_user_id, status, created_at, responded_at
`

type CreateFriendRequestParams struct {
	FromUserID uuid.UUID
	ToUserID   uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.FromUserID, arg.ToUserID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :one
insert into friendship (user_lo, user_hi)
values ($1, $2)
returning id, user_lo, user_hi, created_at
`

type CreateFriendshipParams struct {
	UserLo uuid.UUID
	UserHi uuid.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserLo, arg.UserHi)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserLo,
		&i.UserHi,
		&i.CreatedAt,
	)
	return i, err
}

const createShare = `-- name: CreateShare :exec
insert into friend_cashback_share (bank_client_id, friendship_id)
values ($1, $2)
on conflict do nothing
`

type CreateShareParams struct {
	BankClientID int64
	FriendshipID int64
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) error {
	_, err := q.db.Exec(ctx, createShare, arg.BankClientID, arg.FriendshipID)
	return err
}

const deleteFriendshipByPair = `-- name: DeleteFriendshipByPair :execrows
delete
from friendship
where user_lo = $1
  and user_hi = $2
`

type DeleteFriendshipByPairParams struct {
	UserLo uuid.UUID
	UserHi uuid.UUID
}

func (q *Queries) DeleteFriendshipByPair(ctx context.Context, arg DeleteFriendshipByPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendshipByPair, arg.UserLo, arg.UserHi)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInviteForUser = `-- name: DeleteInviteForUser :execrows
delete
from friend_invite
where id = $1
  and created_by_user_id = $2
`

type DeleteInviteForUserParams struct {
	ID              uuid.UUID
	CreatedByUserID uuid.UUID
}

func (q *Queries) DeleteInviteForUser(ctx context.Context, arg DeleteInviteForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInviteForUser, arg.ID, arg.CreatedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShare = `-- name: DeleteShare :execrows
delete
from friend_cashback_share
where bank_client_id = $1
  and friendship_id = $2
`

type DeleteShareParams struct {
	BankClientID int64
	FriendshipID int64
}

func (q *Queries) DeleteShare(ctx context.Context, arg DeleteShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShare, arg.BankClientID, arg.FriendshipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFriendshipByPair = `-- name: GetFriendshipByPair :one
select id, user_lo, user_hi, created_at
from friendship
where user_lo = $1
  and user_hi = $2
`

type GetFriendshipByPairParams struct {
	UserLo uuid.UUID
	UserHi uuid.UUID
}

func (q *Queries) GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByPair, arg.UserLo, arg.UserHi)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserLo,
		&i.UserHi,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
select id, created_by_user_id, token_hash, created_at, expires_at, claimed_at, claimed_by_user_id
from friend_invite
where token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (FriendInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i FriendInvite
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
	)
	return i, err
}

const getPendingRequestBetween = `-- name: GetPendingRequestBetween :one
select id, from_user_id, to_user_id, status, created_at, responded_at
from friend_request
where status = 'pending'
  and ((from_user_id = $1 and to_user_id = $2) or (from_user_id = $2 and to_user_id = $1))
`

type GetPendingRequestBetweenParams struct {
	FromUserID uuid.UUID
	ToUserID   uuid.UUID
}

func (q *Queries) GetPendingRequestBetween(ctx context.Context, arg GetPendingRequestBetweenParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRequestBetween, arg.FromUserID, arg.ToUserID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getUserByUsernameCI = `-- name: GetUserByUsernameCI :one

select id, username, display_name, email, created_at, telegram_id, password_hash
from "user"
where lower(username) = lower($1)
order by (username = $1) desc
limit 1
`

// Friends module queries. The module owns friendship / friend_request /
// friend_invite / friend_cashback_share; joins to "user" and bank_client are
// read-only reference reads (ADR-0002 seam). The shared-picture read path
// stays in cashback.sql (cashback is the only reader of cashback tables) —
// this file only resolves WHICH clients are visible to whom.
// Exact match, case-insensitive (user_username_lower_idx). username is
// unique only case-sensitively, so two rows can differ by case alone —
// the exact-case row wins then.
func (q *Queries) GetUserByUsernameCI(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameCI, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.TelegramID,
		&i.PasswordHash,
	)
	return i, err
}

const listFriendsForUser = `-- name: ListFriendsForUser :many
select f.id         as friendship_id,
       f.created_at as since,
       u.id         as user_id,
       u.username,
       u.display_name
from friendship f
         join "user" u on u.id = case when f.user_lo = $1 then f.user_hi else f.user_lo end
where f.user_lo = $1
   or f.user_hi = $1
order by u.display_name, u.username
`

type ListFriendsForUserRow struct {
	FriendshipID int64
	Since        time.Time
	UserID       uuid.UUID
	Username     string
	DisplayName  string
}

func (q *Queries) ListFriendsForUser(ctx context.Context, userID uuid.UUID) ([]ListFriendsForUserRow, error) {
	rows, err := q.db.Query(ctx, listFriendsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsForUserRow
	for rows.Next() {
		var i ListFriendsForUserRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.Since,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveInvitesForUser = `-- name: ListLiveInvitesForUser :many
select id, created_by_user_id, token_hash, created_at, expires_at, claimed_at, claimed_by_user_id
from friend_invite
where created_by_user_id = $1
  and claimed_at is null
  and expires_at > now()
order by created_at desc
`

func (q *Queries) ListLiveInvitesForUser(ctx context.Context, createdByUserID uuid.UUID) ([]FriendInvite, error) {
	rows, err := q.db.Query(ctx, listLiveInvitesForUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendInvite
	for rows.Next() {
		var i FriendInvite
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.ClaimedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsForUser = `-- name: ListPendingRequestsForUser :many
select fr.id,
       fr.from_user_id,
       fr.to_user_id,
       fr.created_at,
       fu.username     as from_username,
       fu.display_name as from_display_name,
       tu.username     as to_username,
       tu.display_name as to_display_name
from friend_request fr
         join "user" fu on fu.id = fr.from_user_id
         join "user" tu on tu.id = fr.to_user_id
where fr.status = 'pending'
  and (fr.from_user_id = $1 or fr.to_user_id = $1)
order by fr.created_at desc
`

type ListPendingRequestsForUserRow struct {
	ID              int64
	FromUserID      uuid.UUID
	ToUserID        uuid.UUID
	CreatedAt       time.Time
	FromUsername    string
	FromDisplayName string
	ToUsername      string
	ToDisplayName   string
}

func (q *Queries) ListPendingRequestsForUser(ctx context.Context, userID uuid.UUID) ([]ListPendingRequestsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsForUserRow
	for rows.Next() {
		var i ListPendingRequestsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.CreatedAt,
			&i.FromUsername,
			&i.FromDisplayName,
			&i.ToUsername,
			&i.ToDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedWithViewer = `-- name: ListSharedWithViewer :many
select cl.id      as bank_client_id,
       cl.user_id as owner_user_id,
       u.username,
       u.display_name
from friend_cashback_share s
         join friendship f on f.id = s.friendship_id
         join bank_client cl on cl.id = s.bank_client_id
         join "user" u on u.id = cl.user_id
where (f.user_lo = $1 or f.user_hi = $1)
  and cl.user_id <> $1
order by u.display_name, cl.id
`

type ListSharedWithViewerRow struct {
	BankClientID int64
	OwnerUserID  uuid.UUID
	Username     string
	DisplayName  string
}

// Everything friends currently share with the viewer. The friendship join
// is belt and braces over the FK cascade (invariant 2); grant direction is
// derived, so the viewer's own clients are excluded explicitly.
func (q *Queries) ListSharedWithViewer(ctx context.Context, viewerID uuid.UUID) ([]ListSharedWithViewerRow, error) {
	rows, err := q.db.Query(ctx, listSharedWithViewer, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedWithViewerRow
	for rows.Next() {
		var i ListSharedWithViewerRow
		if err := rows.Scan(
			&i.BankClientID,
			&i.OwnerUserID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForOwner = `-- name: ListSharesForOwner :many
select s.bank_client_id,
       f.id                                                       as friendship_id,
       case when f.user_lo = $1 then f.user_hi else f.user_lo end as friend_user_id
from friend_cashback_share s
         join friendship f on f.id = s.friendship_id
         join bank_client cl on cl.id = s.bank_client_id
where cl.user_id = $1
`

type ListSharesForOwnerRow struct {
	BankClientID int64
	FriendshipID int64
	FriendUserID interface{}
}

// Grants the user has issued: which of their clients each friend sees.
func (q *Queries) ListSharesForOwner(ctx context.Context, ownerID uuid.UUID) ([]ListSharesForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listSharesForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharesForOwnerRow
	for rows.Next() {
		var i ListSharesForOwnerRow
		if err := rows.Scan(&i.BankClientID, &i.FriendshipID, &i.FriendUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestStatusForRecipient = `-- name: SetRequestStatusForRecipient :one
update friend_request
set status       = $3,
    responded_at = now()
where id = $1
  and to_user_id = $2
  and status = 'pending'
returning id, from_user_id, to_user_id, status, created_at, responded_at
`

type SetRequestStatusForRecipientParams struct {
	ID       int64
	ToUserID uuid.UUID
	Status   FriendRequestStatus
}

func (q *Queries) SetRequestStatusForRecipient(ctx context.Context, arg SetRequestStatusForRecipientParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, setRequestStatusForRecipient, arg.ID, arg.ToUserID, arg.Status)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
