// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcc.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMCC = `-- name: GetMCC :one

select code, name, description
from mcc
where code = $1
`

// MCC module queries. Seam note: joins to bank / bank_category /
// canonical_category are the module's read-only reference reads (same seam
// practice as cashback.sql); no other module touches mcc /
// bank_category_mcc / mcc_change. Seed writes via pool.Exec (seed.go
// precedent).
func (q *Queries) GetMCC(ctx context.Context, code int16) (Mcc, error) {
	row := q.db.QueryRow(ctx, getMCC, code)
	var i Mcc
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const listMCCChanges = `-- name: ListMCCChanges :many
select mc.id,
       mc.bank_id,
       b.name as bank_name,
       mc.bank_category_id,
       mc.category_title,
       mc.mcc_code,
       mc.action,
       mc.noted_at,
       mc.source,
       mc.note
from mcc_change mc
         join bank b on b.id = mc.bank_id
order by mc.noted_at desc, mc.id desc
limit $1
`

type ListMCCChangesRow struct {
	ID             int64
	BankID         int32
	BankName       string
	BankCategoryID *int64
	CategoryTitle  string
	MccCode        *int16
	Action         MccChangeAction
	NotedAt        time.Time
	Source         string
	Note           *string
}

func (q *Queries) ListMCCChanges(ctx context.Context, limit int32) ([]ListMCCChangesRow, error) {
	rows, err := q.db.Query(ctx, listMCCChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCCChangesRow
	for rows.Next() {
		var i ListMCCChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.BankCategoryID,
			&i.CategoryTitle,
			&i.MccCode,
			&i.Action,
			&i.NotedAt,
			&i.Source,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMCC = `-- name: ResolveMCC :many
select b.id     as bank_id,
       b.name   as bank_name,
       b.color_hex,
       bc.id    as bank_category_id,
       bc.title,
       bc.kind,
       bc.emoji as bank_emoji,
       cc.emoji as canonical_emoji,
       cc.slug  as canonical_slug,
       cc.title_ru as canonical_title,
       bcm.note
from bank_category_mcc bcm
         join bank_category bc on bc.id = bcm.bank_category_id
         join bank b on b.id = bc.bank_id
         left join canonical_category cc on cc.id = bc.canonical_category_id
where bcm.mcc_code = $1
  and bc.active
order by b.name, bc.title
`

type ResolveMCCRow struct {
	BankID         int32
	BankName       string
	ColorHex       *string
	BankCategoryID int64
	Title          string
	Kind           CashbackOfferKind
	BankEmoji      *string
	CanonicalEmoji *string
	CanonicalSlug  *string
	CanonicalTitle *string
	Note           *string
}

func (q *Queries) ResolveMCC(ctx context.Context, mccCode int16) ([]ResolveMCCRow, error) {
	rows, err := q.db.Query(ctx, resolveMCC, mccCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveMCCRow
	for rows.Next() {
		var i ResolveMCCRow
		if err := rows.Scan(
			&i.BankID,
			&i.BankName,
			&i.ColorHex,
			&i.BankCategoryID,
			&i.Title,
			&i.Kind,
			&i.BankEmoji,
			&i.CanonicalEmoji,
			&i.CanonicalSlug,
			&i.CanonicalTitle,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMCC = `-- name: SearchMCC :many
select code, name, description
from mcc
where case
          when $1::bool
              then lpad(code::text, 4, '0') like $2::text || '%'
          else name ilike '%' || $2::text || '%'
    end
order by code
limit $3
`

type SearchMCCParams struct {
	IsNumeric bool
	Query     string
	MaxRows   int32
}

func (q *Queries) SearchMCC(ctx context.Context, arg SearchMCCParams) ([]Mcc, error) {
	rows, err := q.db.Query(ctx, searchMCC, arg.IsNumeric, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mcc
	for rows.Next() {
		var i Mcc
		if err := rows.Scan(&i.Code, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMerchants = `-- name: SearchMerchants :many
select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       confirmations,
       last_confirmed_at
from point_of_sale
where mcc_code is not null -- a merchant row without an MCC answers nothing here
  and (name ilike '%' || $1::text || '%'
    or merchant_title ilike '%' || $1::text || '%')
order by confirmations desc nulls last, last_confirmed_at desc nulls last, name
limit $2
`

type SearchMerchantsParams struct {
	Query   string
	MaxRows int32
}

type SearchMerchantsRow struct {
	ID              uuid.UUID
	Name            string
	MerchantTitle   *string
	MccCode         *int16
	PosType         string
	Address         *string
	Confirmations   *int64
	LastConfirmedAt *time.Time
}

func (q *Queries) SearchMerchants(ctx context.Context, arg SearchMerchantsParams) ([]SearchMerchantsRow, error) {
	rows, err := q.db.Query(ctx, searchMerchants, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMerchantsRow
	for rows.Next() {
		var i SearchMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.PosType,
			&i.Address,
			&i.Confirmations,
			&i.LastConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
