// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcc.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserPointOfSale = `-- name: CreateUserPointOfSale :one
insert into point_of_sale (name, merchant_title, mcc_code, type, address, status, author_user_id, origin)
values ($1, $2, $3, $4, $5, 'pending', $6, 'user_manual')
returning id, name, merchant_title, mcc_code, type, address, confirmations, created_at, last_confirmed_at, location, status, author_user_id, origin, user_confirmations
`

type CreateUserPointOfSaleParams struct {
	Name          string
	MerchantTitle *string
	MccCode       *int16
	Type          NullPointOfSaleType
	Address       *string
	AuthorUserID  *uuid.UUID
}

func (q *Queries) CreateUserPointOfSale(ctx context.Context, arg CreateUserPointOfSaleParams) (PointOfSale, error) {
	row := q.db.QueryRow(ctx, createUserPointOfSale,
		arg.Name,
		arg.MerchantTitle,
		arg.MccCode,
		arg.Type,
		arg.Address,
		arg.AuthorUserID,
	)
	var i PointOfSale
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantTitle,
		&i.MccCode,
		&i.Type,
		&i.Address,
		&i.Confirmations,
		&i.CreatedAt,
		&i.LastConfirmedAt,
		&i.Location,
		&i.Status,
		&i.AuthorUserID,
		&i.Origin,
		&i.UserConfirmations,
	)
	return i, err
}

const findSimilarPointsOfSale = `-- name: FindSimilarPointsOfSale :many
select id, name, merchant_title, mcc_code
from point_of_sale
where mcc_code = $1
  and (status = 'approved' or (author_user_id = $2::uuid and status = 'pending'))
  and (name ilike '%' || $3::text || '%'
    or $3::text ilike '%' || name || '%')
order by confirmations desc nulls last, name
limit 3
`

type FindSimilarPointsOfSaleParams struct {
	MccCode *int16
	UserID  uuid.UUID
	Name    string
}

type FindSimilarPointsOfSaleRow struct {
	ID            uuid.UUID
	Name          string
	MerchantTitle *string
	MccCode       *int16
}

// The 5e duplicate net: same MCC and either name contains the other —
// «Хлебник» must catch a new «Пекарня Хлебник» before a copy is created.
func (q *Queries) FindSimilarPointsOfSale(ctx context.Context, arg FindSimilarPointsOfSaleParams) ([]FindSimilarPointsOfSaleRow, error) {
	rows, err := q.db.Query(ctx, findSimilarPointsOfSale, arg.MccCode, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarPointsOfSaleRow
	for rows.Next() {
		var i FindSimilarPointsOfSaleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCC = `-- name: GetMCC :one

select code, name, description
from mcc
where code = $1
`

// MCC module queries. Seam note: joins to bank / bank_category /
// canonical_category are the module's read-only reference reads (same seam
// practice as cashback.sql); no other module touches mcc /
// bank_category_mcc / mcc_change. Seed writes via pool.Exec (seed.go
// precedent).
func (q *Queries) GetMCC(ctx context.Context, code int16) (Mcc, error) {
	row := q.db.QueryRow(ctx, getMCC, code)
	var i Mcc
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const listMCCChanges = `-- name: ListMCCChanges :many
select mc.id,
       mc.bank_id,
       b.name as bank_name,
       mc.bank_category_id,
       mc.category_title,
       mc.mcc_code,
       mc.action,
       mc.noted_at,
       mc.source,
       mc.note
from mcc_change mc
         join bank b on b.id = mc.bank_id
order by mc.noted_at desc, mc.id desc
limit $1
`

type ListMCCChangesRow struct {
	ID             int64
	BankID         int32
	BankName       string
	BankCategoryID *int64
	CategoryTitle  string
	MccCode        *int16
	Action         MccChangeAction
	NotedAt        time.Time
	Source         string
	Note           *string
}

func (q *Queries) ListMCCChanges(ctx context.Context, limit int32) ([]ListMCCChangesRow, error) {
	rows, err := q.db.Query(ctx, listMCCChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCCChangesRow
	for rows.Next() {
		var i ListMCCChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.BankCategoryID,
			&i.CategoryTitle,
			&i.MccCode,
			&i.Action,
			&i.NotedAt,
			&i.Source,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderationApprovePOS = `-- name: ModerationApprovePOS :execrows
update point_of_sale
set status = 'approved'
where id = $1
  and status = 'pending'
`

func (q *Queries) ModerationApprovePOS(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, moderationApprovePOS, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moderationListPendingPOS = `-- name: ModerationListPendingPOS :many

select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       origin::text                   as origin,
       created_at,
       count(*) over ()::bigint       as total
from point_of_sale
where status = 'pending'
order by created_at, id
limit $2 offset $1
`

type ModerationListPendingPOSParams struct {
	Skip    int32
	MaxRows int32
}

type ModerationListPendingPOSRow struct {
	ID            uuid.UUID
	Name          string
	MerchantTitle *string
	MccCode       *int16
	PosType       string
	Address       *string
	Origin        string
	CreatedAt     time.Time
	Total         int64
}

// Moderation (roles-moderation.md). The queue is ANONYMOUS by column
// selection: author_user_id is deliberately never selected here — the
// moderator-facing DTO cannot carry what the query never returns
// (invariant 1). Writes are scoped to non-scrape rows: the 62k imported
// rows are the operator's domain (sidecar), not the moderators'.
func (q *Queries) ModerationListPendingPOS(ctx context.Context, arg ModerationListPendingPOSParams) ([]ModerationListPendingPOSRow, error) {
	rows, err := q.db.Query(ctx, moderationListPendingPOS, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationListPendingPOSRow
	for rows.Next() {
		var i ModerationListPendingPOSRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.PosType,
			&i.Address,
			&i.Origin,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderationListPublishedPOS = `-- name: ModerationListPublishedPOS :many
select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       origin::text                   as origin,
       created_at,
       count(*) over ()::bigint       as total
from point_of_sale
where status = 'approved'
  and origin <> 'mcc_codes'
order by created_at desc, id
limit $2 offset $1
`

type ModerationListPublishedPOSParams struct {
	Skip    int32
	MaxRows int32
}

type ModerationListPublishedPOSRow struct {
	ID            uuid.UUID
	Name          string
	MerchantTitle *string
	MccCode       *int16
	PosType       string
	Address       *string
	Origin        string
	CreatedAt     time.Time
	Total         int64
}

// The review stream: recently published non-scrape rows — what keeps the
// instant-publish path (user_transaction) supervised after the fact.
func (q *Queries) ModerationListPublishedPOS(ctx context.Context, arg ModerationListPublishedPOSParams) ([]ModerationListPublishedPOSRow, error) {
	rows, err := q.db.Query(ctx, moderationListPublishedPOS, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationListPublishedPOSRow
	for rows.Next() {
		var i ModerationListPublishedPOSRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.PosType,
			&i.Address,
			&i.Origin,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderationRejectPOS = `-- name: ModerationRejectPOS :execrows
update point_of_sale
set status = 'rejected'
where id = $1
  and status in ('pending', 'approved')
  and origin <> 'mcc_codes'
`

// Reject doubles as the review stream's prune: a published non-scrape row
// can be pulled back. Rejected rows are kept for audit.
func (q *Queries) ModerationRejectPOS(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, moderationRejectPOS, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveMCC = `-- name: ResolveMCC :many
select b.id     as bank_id,
       b.name   as bank_name,
       b.color_hex,
       bc.id    as bank_category_id,
       bc.title,
       bc.kind,
       bc.emoji as bank_emoji,
       cc.emoji as canonical_emoji,
       cc.slug  as canonical_slug,
       cc.title_ru as canonical_title,
       bcm.note
from bank_category_mcc bcm
         join bank_category bc on bc.id = bcm.bank_category_id
         join bank b on b.id = bc.bank_id
         left join canonical_category cc on cc.id = bc.canonical_category_id
where bcm.mcc_code = $1
  and bc.active
order by b.name, bc.title
`

type ResolveMCCRow struct {
	BankID         int32
	BankName       string
	ColorHex       *string
	BankCategoryID int64
	Title          string
	Kind           CashbackOfferKind
	BankEmoji      *string
	CanonicalEmoji *string
	CanonicalSlug  *string
	CanonicalTitle *string
	Note           *string
}

func (q *Queries) ResolveMCC(ctx context.Context, mccCode int16) ([]ResolveMCCRow, error) {
	rows, err := q.db.Query(ctx, resolveMCC, mccCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveMCCRow
	for rows.Next() {
		var i ResolveMCCRow
		if err := rows.Scan(
			&i.BankID,
			&i.BankName,
			&i.ColorHex,
			&i.BankCategoryID,
			&i.Title,
			&i.Kind,
			&i.BankEmoji,
			&i.CanonicalEmoji,
			&i.CanonicalSlug,
			&i.CanonicalTitle,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMCC = `-- name: SearchMCC :many
select code, name, description
from mcc
where case
          when $1::bool
              then lpad(code::text, 4, '0') like $2::text || '%'
          else name ilike '%' || $2::text || '%'
    end
order by code
limit $3
`

type SearchMCCParams struct {
	IsNumeric bool
	Query     string
	MaxRows   int32
}

func (q *Queries) SearchMCC(ctx context.Context, arg SearchMCCParams) ([]Mcc, error) {
	rows, err := q.db.Query(ctx, searchMCC, arg.IsNumeric, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mcc
	for rows.Next() {
		var i Mcc
		if err := rows.Scan(&i.Code, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMerchants = `-- name: SearchMerchants :many
select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       confirmations,
       user_confirmations,
       last_confirmed_at,
       status,
       origin::text as origin
from point_of_sale
where mcc_code is not null -- a merchant row without an MCC answers nothing here
  and (status = 'approved' or (author_user_id = $1::uuid and status = 'pending'))
  and (name ilike '%' || $2::text || '%'
    or merchant_title ilike '%' || $2::text || '%')
order by confirmations desc nulls last, last_confirmed_at desc nulls last, name
limit $3
`

type SearchMerchantsParams struct {
	UserID  uuid.UUID
	Query   string
	MaxRows int32
}

type SearchMerchantsRow struct {
	ID                uuid.UUID
	Name              string
	MerchantTitle     *string
	MccCode           *int16
	PosType           string
	Address           *string
	Confirmations     *int64
	UserConfirmations int64
	LastConfirmedAt   *time.Time
	Status            PointOfSaleStatus
	Origin            string
}

// Pending user submissions are visible to their author only (5e): the общий
// каталог serves approved rows. Rejected rows are invisible to everyone,
// the author included (roles-moderation invariant 3).
func (q *Queries) SearchMerchants(ctx context.Context, arg SearchMerchantsParams) ([]SearchMerchantsRow, error) {
	rows, err := q.db.Query(ctx, searchMerchants, arg.UserID, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMerchantsRow
	for rows.Next() {
		var i SearchMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.PosType,
			&i.Address,
			&i.Confirmations,
			&i.UserConfirmations,
			&i.LastConfirmedAt,
			&i.Status,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
