// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcc.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserPointOfSale = `-- name: CreateUserPointOfSale :one
insert into point_of_sale (name, merchant_title, mcc_code, type, address, status, author_user_id)
values ($1, $2, $3, $4, $5, 'pending', $6)
returning id, name, merchant_title, mcc_code, type, address, confirmations, created_at, last_confirmed_at, location, status, author_user_id
`

type CreateUserPointOfSaleParams struct {
	Name          string
	MerchantTitle *string
	MccCode       *int16
	Type          NullPointOfSaleType
	Address       *string
	AuthorUserID  *uuid.UUID
}

func (q *Queries) CreateUserPointOfSale(ctx context.Context, arg CreateUserPointOfSaleParams) (PointOfSale, error) {
	row := q.db.QueryRow(ctx, createUserPointOfSale,
		arg.Name,
		arg.MerchantTitle,
		arg.MccCode,
		arg.Type,
		arg.Address,
		arg.AuthorUserID,
	)
	var i PointOfSale
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantTitle,
		&i.MccCode,
		&i.Type,
		&i.Address,
		&i.Confirmations,
		&i.CreatedAt,
		&i.LastConfirmedAt,
		&i.Location,
		&i.Status,
		&i.AuthorUserID,
	)
	return i, err
}

const findSimilarPointsOfSale = `-- name: FindSimilarPointsOfSale :many
select id, name, merchant_title, mcc_code
from point_of_sale
where mcc_code = $1
  and (status = 'approved' or author_user_id = $2::uuid)
  and (name ilike '%' || $3::text || '%'
    or $3::text ilike '%' || name || '%')
order by confirmations desc nulls last, name
limit 3
`

type FindSimilarPointsOfSaleParams struct {
	MccCode *int16
	UserID  uuid.UUID
	Name    string
}

type FindSimilarPointsOfSaleRow struct {
	ID            uuid.UUID
	Name          string
	MerchantTitle *string
	MccCode       *int16
}

// The 5e duplicate net: same MCC and either name contains the other —
// «Хлебник» must catch a new «Пекарня Хлебник» before a copy is created.
func (q *Queries) FindSimilarPointsOfSale(ctx context.Context, arg FindSimilarPointsOfSaleParams) ([]FindSimilarPointsOfSaleRow, error) {
	rows, err := q.db.Query(ctx, findSimilarPointsOfSale, arg.MccCode, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarPointsOfSaleRow
	for rows.Next() {
		var i FindSimilarPointsOfSaleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCC = `-- name: GetMCC :one

select code, name, description
from mcc
where code = $1
`

// MCC module queries. Seam note: joins to bank / bank_category /
// canonical_category are the module's read-only reference reads (same seam
// practice as cashback.sql); no other module touches mcc /
// bank_category_mcc / mcc_change. Seed writes via pool.Exec (seed.go
// precedent).
func (q *Queries) GetMCC(ctx context.Context, code int16) (Mcc, error) {
	row := q.db.QueryRow(ctx, getMCC, code)
	var i Mcc
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const getPointOfSale = `-- name: GetPointOfSale :one
select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       confirmations,
       last_confirmed_at,
       status
from point_of_sale
where id = $1
  and (status = 'approved' or author_user_id = $2::uuid)
`

type GetPointOfSaleParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetPointOfSaleRow struct {
	ID              uuid.UUID
	Name            string
	MerchantTitle   *string
	MccCode         *int16
	PosType         string
	Address         *string
	Confirmations   *int64
	LastConfirmedAt *time.Time
	Status          PointOfSaleStatus
}

// The «О точке» card (8b): one row by id — approved, or the caller's own
// pending submission (the same visibility rule the search applies).
func (q *Queries) GetPointOfSale(ctx context.Context, arg GetPointOfSaleParams) (GetPointOfSaleRow, error) {
	row := q.db.QueryRow(ctx, getPointOfSale, arg.ID, arg.UserID)
	var i GetPointOfSaleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantTitle,
		&i.MccCode,
		&i.PosType,
		&i.Address,
		&i.Confirmations,
		&i.LastConfirmedAt,
		&i.Status,
	)
	return i, err
}

const listMCCChanges = `-- name: ListMCCChanges :many
select mc.id,
       mc.bank_id,
       b.name as bank_name,
       mc.bank_category_id,
       mc.category_title,
       mc.mcc_code,
       mc.action,
       mc.noted_at,
       mc.source,
       mc.note
from mcc_change mc
         join bank b on b.id = mc.bank_id
order by mc.noted_at desc, mc.id desc
limit $1
`

type ListMCCChangesRow struct {
	ID             int64
	BankID         int32
	BankName       string
	BankCategoryID *int64
	CategoryTitle  string
	MccCode        *int16
	Action         MccChangeAction
	NotedAt        time.Time
	Source         string
	Note           *string
}

func (q *Queries) ListMCCChanges(ctx context.Context, limit int32) ([]ListMCCChangesRow, error) {
	rows, err := q.db.Query(ctx, listMCCChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCCChangesRow
	for rows.Next() {
		var i ListMCCChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.BankName,
			&i.BankCategoryID,
			&i.CategoryTitle,
			&i.MccCode,
			&i.Action,
			&i.NotedAt,
			&i.Source,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMCC = `-- name: ResolveMCC :many
select b.id     as bank_id,
       b.name   as bank_name,
       b.color_hex,
       bc.id    as bank_category_id,
       bc.title,
       bc.kind,
       bc.emoji as bank_emoji,
       cc.emoji as canonical_emoji,
       cc.slug  as canonical_slug,
       cc.title_ru as canonical_title,
       bcm.note
from bank_category_mcc bcm
         join bank_category bc on bc.id = bcm.bank_category_id
         join bank b on b.id = bc.bank_id
         left join canonical_category cc on cc.id = bc.canonical_category_id
where bcm.mcc_code = $1
  and bc.active
order by b.name, bc.title
`

type ResolveMCCRow struct {
	BankID         int32
	BankName       string
	ColorHex       *string
	BankCategoryID int64
	Title          string
	Kind           CashbackOfferKind
	BankEmoji      *string
	CanonicalEmoji *string
	CanonicalSlug  *string
	CanonicalTitle *string
	Note           *string
}

func (q *Queries) ResolveMCC(ctx context.Context, mccCode int16) ([]ResolveMCCRow, error) {
	rows, err := q.db.Query(ctx, resolveMCC, mccCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveMCCRow
	for rows.Next() {
		var i ResolveMCCRow
		if err := rows.Scan(
			&i.BankID,
			&i.BankName,
			&i.ColorHex,
			&i.BankCategoryID,
			&i.Title,
			&i.Kind,
			&i.BankEmoji,
			&i.CanonicalEmoji,
			&i.CanonicalSlug,
			&i.CanonicalTitle,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMCC = `-- name: SearchMCC :many
select code, name, description
from mcc
where case
          when $1::bool
              then lpad(code::text, 4, '0') like $2::text || '%'
          else name ilike '%' || $2::text || '%'
    end
order by code
limit $3
`

type SearchMCCParams struct {
	IsNumeric bool
	Query     string
	MaxRows   int32
}

func (q *Queries) SearchMCC(ctx context.Context, arg SearchMCCParams) ([]Mcc, error) {
	rows, err := q.db.Query(ctx, searchMCC, arg.IsNumeric, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mcc
	for rows.Next() {
		var i Mcc
		if err := rows.Scan(&i.Code, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMerchants = `-- name: SearchMerchants :many
select id,
       name,
       merchant_title,
       mcc_code,
       coalesce(type::text, '')::text as pos_type,
       address,
       confirmations,
       last_confirmed_at,
       status,
       count(*) over ()::bigint as total_rows
from point_of_sale
where mcc_code is not null -- a merchant row without an MCC answers nothing here
  and (status = 'approved' or author_user_id = $1::uuid)
  -- The first word, per column and without coalesce, is the clause the two
  -- gin_trgm_ops indexes can serve: a BitmapOr over name/merchant_title
  -- instead of a 62k-row scan (11 ms vs 115 ms on the live base). It is
  -- implied by the ALL below, so it changes no result — only the plan.
  and (name ilike $2::text or merchant_title ilike $2::text)
  -- Every word, against the two fields joined. Matching the concatenation is
  -- the same as matching either column, because the words come from a
  -- whitespace split: a spaceless pattern cannot straddle the joining space.
  and name || ' ' || coalesce(merchant_title, '') ilike all ($3::text[])
order by confirmations desc nulls last, last_confirmed_at desc nulls last, name, id
limit $5 offset $4
`

type SearchMerchantsParams struct {
	UserID   uuid.UUID
	Head     string
	Patterns []string
	SkipRows int32
	MaxRows  int32
}

type SearchMerchantsRow struct {
	ID              uuid.UUID
	Name            string
	MerchantTitle   *string
	MccCode         *int16
	PosType         string
	Address         *string
	Confirmations   *int64
	LastConfirmedAt *time.Time
	Status          PointOfSaleStatus
	TotalRows       int64
}

// Pending user submissions are visible to their author only (5e): the общий
// каталог serves approved rows.
// Every word of the query must appear somewhere in the row, in any order:
// «доставка яндекс» and «яндекс доставка» are the same question. The words
// arrive already wrapped in %…% (the service builds them).
//
// total_rows rides along as a window count over the whole match set: the
// caller pages with offset, and «яндекс» matches 500+ rows — without the
// count the list would silently end at the page size, which is exactly the
// bug this replaced (a row found by «яндекс доставка» was missing from
// «яндекс», buried past row 20 by the confirmations order).
// id last: offset paging needs a total order, or a row can repeat or vanish
// between pages when confirmations tie (they tie constantly — most rows sit
// at 0).
func (q *Queries) SearchMerchants(ctx context.Context, arg SearchMerchantsParams) ([]SearchMerchantsRow, error) {
	rows, err := q.db.Query(ctx, searchMerchants,
		arg.UserID,
		arg.Head,
		arg.Patterns,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMerchantsRow
	for rows.Next() {
		var i SearchMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantTitle,
			&i.MccCode,
			&i.PosType,
			&i.Address,
			&i.Confirmations,
			&i.LastConfirmedAt,
			&i.Status,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
