// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type CashbackCapScope string

const (
	CashbackCapScopeTotal       CashbackCapScope = "total"
	CashbackCapScopePerCategory CashbackCapScope = "per_category"
	CashbackCapScopeBoth        CashbackCapScope = "both"
)

func (e *CashbackCapScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashbackCapScope(s)
	case string:
		*e = CashbackCapScope(s)
	default:
		return fmt.Errorf("unsupported scan type for CashbackCapScope: %T", src)
	}
	return nil
}

type NullCashbackCapScope struct {
	CashbackCapScope CashbackCapScope
	Valid            bool // Valid is true if CashbackCapScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashbackCapScope) Scan(value interface{}) error {
	if value == nil {
		ns.CashbackCapScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashbackCapScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashbackCapScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashbackCapScope), nil
}

type CashbackCurrencyKind string

const (
	CashbackCurrencyKindRub    CashbackCurrencyKind = "rub"
	CashbackCurrencyKindPoints CashbackCurrencyKind = "points"
)

func (e *CashbackCurrencyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashbackCurrencyKind(s)
	case string:
		*e = CashbackCurrencyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CashbackCurrencyKind: %T", src)
	}
	return nil
}

type NullCashbackCurrencyKind struct {
	CashbackCurrencyKind CashbackCurrencyKind
	Valid                bool // Valid is true if CashbackCurrencyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashbackCurrencyKind) Scan(value interface{}) error {
	if value == nil {
		ns.CashbackCurrencyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashbackCurrencyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashbackCurrencyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashbackCurrencyKind), nil
}

type CashbackOfferKind string

const (
	CashbackOfferKindRegular CashbackOfferKind = "regular"
	CashbackOfferKindSpecial CashbackOfferKind = "special"
)

func (e *CashbackOfferKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashbackOfferKind(s)
	case string:
		*e = CashbackOfferKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CashbackOfferKind: %T", src)
	}
	return nil
}

type NullCashbackOfferKind struct {
	CashbackOfferKind CashbackOfferKind
	Valid             bool // Valid is true if CashbackOfferKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashbackOfferKind) Scan(value interface{}) error {
	if value == nil {
		ns.CashbackOfferKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashbackOfferKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashbackOfferKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashbackOfferKind), nil
}

type CashbackPeriodType string

const (
	CashbackPeriodTypeCalendarMonth CashbackPeriodType = "calendar_month"
	CashbackPeriodTypeQuarter       CashbackPeriodType = "quarter"
	CashbackPeriodTypeWeek          CashbackPeriodType = "week"
	CashbackPeriodTypeRolling       CashbackPeriodType = "rolling"
)

func (e *CashbackPeriodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashbackPeriodType(s)
	case string:
		*e = CashbackPeriodType(s)
	default:
		return fmt.Errorf("unsupported scan type for CashbackPeriodType: %T", src)
	}
	return nil
}

type NullCashbackPeriodType struct {
	CashbackPeriodType CashbackPeriodType
	Valid              bool // Valid is true if CashbackPeriodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashbackPeriodType) Scan(value interface{}) error {
	if value == nil {
		ns.CashbackPeriodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashbackPeriodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashbackPeriodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashbackPeriodType), nil
}

type CashbackSelectionMode string

const (
	CashbackSelectionModeAtomic      CashbackSelectionMode = "atomic"
	CashbackSelectionModeIncremental CashbackSelectionMode = "incremental"
)

func (e *CashbackSelectionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashbackSelectionMode(s)
	case string:
		*e = CashbackSelectionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CashbackSelectionMode: %T", src)
	}
	return nil
}

type NullCashbackSelectionMode struct {
	CashbackSelectionMode CashbackSelectionMode
	Valid                 bool // Valid is true if CashbackSelectionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashbackSelectionMode) Scan(value interface{}) error {
	if value == nil {
		ns.CashbackSelectionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashbackSelectionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashbackSelectionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashbackSelectionMode), nil
}

type PaymentSystem string

const (
	PaymentSystemVisa            PaymentSystem = "visa"
	PaymentSystemMastercard      PaymentSystem = "mastercard"
	PaymentSystemMir             PaymentSystem = "mir"
	PaymentSystemUnionpay        PaymentSystem = "unionpay"
	PaymentSystemAmericanExpress PaymentSystem = "american_express"
)

func (e *PaymentSystem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentSystem(s)
	case string:
		*e = PaymentSystem(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentSystem: %T", src)
	}
	return nil
}

type NullPaymentSystem struct {
	PaymentSystem PaymentSystem
	Valid         bool // Valid is true if PaymentSystem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentSystem) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentSystem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentSystem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentSystem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentSystem), nil
}

type Period string

const (
	PeriodDay   Period = "day"
	PeriodWeek  Period = "week"
	PeriodMonth Period = "month"
	PeriodYear  Period = "year"
)

func (e *Period) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Period(s)
	case string:
		*e = Period(s)
	default:
		return fmt.Errorf("unsupported scan type for Period: %T", src)
	}
	return nil
}

type NullPeriod struct {
	Period Period
	Valid  bool // Valid is true if Period is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.Period, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Period.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Period), nil
}

type PointOfSaleType string

const (
	PointOfSaleTypeOffline PointOfSaleType = "offline"
	PointOfSaleTypeOnline  PointOfSaleType = "online"
	PointOfSaleTypeApp     PointOfSaleType = "app"
	PointOfSaleTypeOther   PointOfSaleType = "other"
)

func (e *PointOfSaleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PointOfSaleType(s)
	case string:
		*e = PointOfSaleType(s)
	default:
		return fmt.Errorf("unsupported scan type for PointOfSaleType: %T", src)
	}
	return nil
}

type NullPointOfSaleType struct {
	PointOfSaleType PointOfSaleType
	Valid           bool // Valid is true if PointOfSaleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPointOfSaleType) Scan(value interface{}) error {
	if value == nil {
		ns.PointOfSaleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PointOfSaleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPointOfSaleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PointOfSaleType), nil
}

type TransactionDirection string

const (
	TransactionDirectionExpense TransactionDirection = "expense"
	TransactionDirectionIncome  TransactionDirection = "income"
)

func (e *TransactionDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionDirection(s)
	case string:
		*e = TransactionDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionDirection: %T", src)
	}
	return nil
}

type NullTransactionDirection struct {
	TransactionDirection TransactionDirection
	Valid                bool // Valid is true if TransactionDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionDirection) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionDirection), nil
}

type TransactionStatus string

const (
	TransactionStatusHold    TransactionStatus = "hold"
	TransactionStatusSuccess TransactionStatus = "success"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus
	Valid             bool // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type Article struct {
	ID    int32
	Title string
	Text  string
}

type Attachment struct {
	ID        uuid.UUID
	Filename  string
	MediaType *string
	UserID    *uuid.UUID
}

type Bank struct {
	ID           int32
	Name         string
	LogoFilename *string
	ColorHex     *string
}

type BankCard struct {
	ID            int32
	BankID        int16
	UserID        uuid.UUID
	Last4Digits   int32
	PaymentSystem PaymentSystem
	ImageFilename *string
	ProgramTierID *int64
	// Family member holding this plastic; null = the account owner themselves
	HolderLabel *string
}

type BankCategoryAlias struct {
	CanonicalCategoryID int64
	BankID              int32
	RawTitle            string
}

type BankMcc struct {
	BankID   int16
	MccCode  int16
	Footnote *string
}

type CanonicalCategory struct {
	ID      int64
	Slug    string
	TitleRu string
}

type CashbackProgram struct {
	ID                int64
	BankID            int32
	Name              string
	PeriodType        CashbackPeriodType
	SelectionMode     CashbackSelectionMode
	CurrencyKind      CashbackCurrencyKind
	PointsLabel       *string
	SelectionOpensDay *int32
	Notes             *string
}

type Category struct {
	ID                       int32
	BankID                   int16
	Name                     string
	Description              *string
	MccAdditionalDescription *string
	IconFilename             *string
	OgID                     *int32
}

type CategoryMcc struct {
	CategoryID int32
	MccCode    int16
}

type CategoryOffer struct {
	ID                  int64
	OfferPeriodID       int64
	RawTitle            string
	CanonicalCategoryID *int64
	Percent             *decimal.Decimal
	Kind                CashbackOfferKind
	Notes               *string
}

type Mcc struct {
	Code        int16
	Name        string
	Description *string
}

type OfferPeriod struct {
	ID          int64
	CardID      int32
	PeriodStart time.Time
	PeriodEnd   time.Time
	// Per-period slot count; null = use tier.max_categories (invariant 1 uses the effective value)
	MaxCategoriesOverride *int32
}

type OfferPeriodAttachment struct {
	OfferPeriodID int64
	AttachmentID  uuid.UUID
}

type PartnerOffer struct {
	ID            int64
	UserID        uuid.UUID
	BankID        int32
	CardID        *int32
	MerchantTitle string
	Percent       *decimal.Decimal
	ValidFrom     *time.Time
	ValidTo       *time.Time
	CapValue      *decimal.Decimal
	Notes         *string
}

type PartnerOfferAttachment struct {
	PartnerOfferID int64
	AttachmentID   uuid.UUID
}

type PointOfSale struct {
	ID              uuid.UUID
	Name            string
	MerchantTitle   *string
	MccCode         *int16
	Type            NullPointOfSaleType
	Address         *string
	Confirmations   *int64
	CreatedAt       time.Time
	LastConfirmedAt *time.Time
	Location        interface{}
}

type ProgramTier struct {
	ID                 int64
	ProgramID          int64
	Name               string
	IsPaidSubscription bool
	CapValue           *decimal.Decimal
	CapScope           CashbackCapScope
	CapPerCategory     *decimal.Decimal
	MaxCategories      *int32
	BasePercent        *decimal.Decimal
	Notes              *string
}

type ReceiptPosition struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	Name          string
	Quantity      float32
	Total         interface{}
}

type Selection struct {
	ID              int64
	CategoryOfferID int64
	SelectedAt      time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Subscription struct {
	ID                 int32
	Name               string
	Price              interface{}
	RecurrenceDate     time.Time
	RecurrenceInterval pgtype.Interval
	BankCardID         *int32
	IsActive           pgtype.Bool
	Notes              *string
	IconFilename       *string
}

type SubscriptionMember struct {
	SubscriptionID int32
	UserID         uuid.UUID
	Since          time.Time
	IsPayer        bool
}

type Transaction struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	OgID                string
	Timestamp           time.Time
	Title               string
	Amount              interface{}
	Direction           TransactionDirection
	BankID              *int16
	MerchandiserLogoUrl *string
	BankComment         *string
	MccCode             *int16
	CategoryID          *int32
	LoyaltyAmount       interface{}
	Status              TransactionStatus
	Location            interface{}
	BankCardID          *int32
	SubscriptionID      *int32
	UserComment         *string
}

type TransactionAttachment struct {
	TransactionID uuid.UUID
	AttachmentID  uuid.UUID
}

type TransactionUser struct {
	TransactionID     uuid.UUID
	UserID            uuid.UUID
	PositionID        *uuid.UUID
	EqualDistribution bool
}

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  string
	Email        string
	CreatedAt    time.Time
	TelegramID   *int64
	PasswordHash *string
}
