// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: perks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPerkQuotaHistory = `-- name: CountPerkQuotaHistory :one
select (select count(*) from perk_event e where e.quota_id = $1)    as events,
       (select count(*) from perk_snapshot s where s.quota_id = $1) as snapshots
`

type CountPerkQuotaHistoryRow struct {
	Events    int64
	Snapshots int64
}

// CountPerkQuotaHistory answers «has this window been used yet?» — the gate on
// editing `size` in place instead of dating a resize event.
func (q *Queries) CountPerkQuotaHistory(ctx context.Context, quotaID int64) (CountPerkQuotaHistoryRow, error) {
	row := q.db.QueryRow(ctx, countPerkQuotaHistory, quotaID)
	var i CountPerkQuotaHistoryRow
	err := row.Scan(&i.Events, &i.Snapshots)
	return i, err
}

const createPerk = `-- name: CreatePerk :one

insert into perk (user_id, bank_client_id, name, unit, note)
select cl.user_id, cl.id, $1, $2, $3
from bank_client cl
where cl.id = $4
  and cl.user_id = $5
returning id, user_id, name, unit, note, created_at, bank_client_id
`

type CreatePerkParams struct {
	Name         string
	Unit         string
	Note         *string
	BankClientID int64
	UserID       uuid.UUID
}

// Привилегии module queries (docs/specs/perks.md). The module owns perk /
// perk_quota / perk_event / perk_snapshot; bank and bank_client are read-only
// reference reads (ADR-0002 seam) — no cashback table is touched here, and
// nothing outside the module reads these four.
//
// Since 00025 a perk belongs to a держатель: `perk.bank_client_id` is the
// module's anchor, the bank is read through it, and a window inherits both
// from its perk.
//
// Nothing in this file computes remaining. The math (effective size, consumed
// across both levels, the discrepancy predicate) lives in internal/perks/
// domain.go where it is pure and tested; these queries return the raw ledger
// and let it do the arithmetic.
// CreatePerk authorizes through the держатель, the CreateCard idiom: the
// insert reads bank_client scoped by the session user, so a foreign or missing
// client yields 0 rows → 404.
func (q *Queries) CreatePerk(ctx context.Context, arg CreatePerkParams) (Perk, error) {
	row := q.db.QueryRow(ctx, createPerk,
		arg.Name,
		arg.Unit,
		arg.Note,
		arg.BankClientID,
		arg.UserID,
	)
	var i Perk
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Unit,
		&i.Note,
		&i.CreatedAt,
		&i.BankClientID,
	)
	return i, err
}

const createPerkEvent = `-- name: CreatePerkEvent :one
insert into perk_event (quota_id, kind, qty, event_date, note)
select q.id, $1::perk_event_kind, $2, $3, $4
from perk_quota q
         join perk p on p.id = q.perk_id
where q.id = $5
  and p.user_id = $6
returning id, quota_id, kind, qty, event_date, note, created_at
`

type CreatePerkEventParams struct {
	Kind      PerkEventKind
	Qty       int32
	EventDate time.Time
	Note      *string
	QuotaID   int64
	UserID    uuid.UUID
}

// CreatePerkEvent authorizes through the owning perk, the CreatePerkQuota
// idiom: 0 rows means the quota is missing or someone else's.
func (q *Queries) CreatePerkEvent(ctx context.Context, arg CreatePerkEventParams) (PerkEvent, error) {
	row := q.db.QueryRow(ctx, createPerkEvent,
		arg.Kind,
		arg.Qty,
		arg.EventDate,
		arg.Note,
		arg.QuotaID,
		arg.UserID,
	)
	var i PerkEvent
	err := row.Scan(
		&i.ID,
		&i.QuotaID,
		&i.Kind,
		&i.Qty,
		&i.EventDate,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createPerkQuota = `-- name: CreatePerkQuota :one
insert into perk_quota (perk_id, parent_quota_id, window_start, window_end, size, note)
select p.id, $1, $2, $3, $4, $5
from perk p
where p.id = $6
  and p.user_id = $7
returning id, perk_id, parent_quota_id, window_start, window_end, size, note, created_at, is_child, parent_is_root
`

type CreatePerkQuotaParams struct {
	ParentQuotaID *int64
	WindowStart   time.Time
	WindowEnd     time.Time
	Size          int32
	Note          *string
	PerkID        int64
	UserID        uuid.UUID
}

// CreatePerkQuota authorizes through the owning perk: 0 rows means the perk is
// missing or someone else's. The держатель needs no checking — the window
// inherits it (00025).
func (q *Queries) CreatePerkQuota(ctx context.Context, arg CreatePerkQuotaParams) (PerkQuotum, error) {
	row := q.db.QueryRow(ctx, createPerkQuota,
		arg.ParentQuotaID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Size,
		arg.Note,
		arg.PerkID,
		arg.UserID,
	)
	var i PerkQuotum
	err := row.Scan(
		&i.ID,
		&i.PerkID,
		&i.ParentQuotaID,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Size,
		&i.Note,
		&i.CreatedAt,
		&i.IsChild,
		&i.ParentIsRoot,
	)
	return i, err
}

const createPerkSnapshot = `-- name: CreatePerkSnapshot :one
insert into perk_snapshot (quota_id, observed_on, remaining, note)
select q.id, $1, $2, $3
from perk_quota q
         join perk p on p.id = q.perk_id
where q.id = $4
  and p.user_id = $5
returning id, quota_id, observed_on, remaining, note, created_at
`

type CreatePerkSnapshotParams struct {
	ObservedOn time.Time
	Remaining  int32
	Note       *string
	QuotaID    int64
	UserID     uuid.UUID
}

func (q *Queries) CreatePerkSnapshot(ctx context.Context, arg CreatePerkSnapshotParams) (PerkSnapshot, error) {
	row := q.db.QueryRow(ctx, createPerkSnapshot,
		arg.ObservedOn,
		arg.Remaining,
		arg.Note,
		arg.QuotaID,
		arg.UserID,
	)
	var i PerkSnapshot
	err := row.Scan(
		&i.ID,
		&i.QuotaID,
		&i.ObservedOn,
		&i.Remaining,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deletePerkEventForUser = `-- name: DeletePerkEventForUser :execrows
delete
from perk_event e using perk_quota q, perk p
where q.id = e.quota_id
  and p.id = q.perk_id
  and e.id = $1
  and p.user_id = $2
`

type DeletePerkEventForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeletePerkEventForUser(ctx context.Context, arg DeletePerkEventForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerkEventForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePerkForUser = `-- name: DeletePerkForUser :execrows
delete
from perk
where id = $1
  and user_id = $2
`

type DeletePerkForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

// DeletePerkForUser leaves the 409 to the caller: perk_quota.perk_id is a plain
// FK, so a perk with windows fails with 23503 rather than taking a ledger down
// with it (spec invariant 6).
func (q *Queries) DeletePerkForUser(ctx context.Context, arg DeletePerkForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerkForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePerkQuotaForUser = `-- name: DeletePerkQuotaForUser :execrows
delete
from perk_quota q using perk p
where p.id = q.perk_id
  and q.id = $1
  and p.user_id = $2
`

type DeletePerkQuotaForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeletePerkQuotaForUser(ctx context.Context, arg DeletePerkQuotaForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerkQuotaForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePerkSnapshotForUser = `-- name: DeletePerkSnapshotForUser :execrows
delete
from perk_snapshot s using perk_quota q, perk p
where q.id = s.quota_id
  and p.id = q.perk_id
  and s.id = $1
  and p.user_id = $2
`

type DeletePerkSnapshotForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeletePerkSnapshotForUser(ctx context.Context, arg DeletePerkSnapshotForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerkSnapshotForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPerkForUser = `-- name: GetPerkForUser :one
select p.id, p.user_id, p.name, p.unit, p.note, p.created_at, p.bank_client_id, cl.bank_id, cl.label as client_label, b.name as bank_name
from perk p
         join bank_client cl on cl.id = p.bank_client_id
         join bank b on b.id = cl.bank_id
where p.id = $1
  and p.user_id = $2
`

type GetPerkForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetPerkForUserRow struct {
	ID           int64
	UserID       uuid.UUID
	Name         string
	Unit         string
	Note         *string
	CreatedAt    time.Time
	BankClientID int64
	BankID       int32
	ClientLabel  *string
	BankName     string
}

func (q *Queries) GetPerkForUser(ctx context.Context, arg GetPerkForUserParams) (GetPerkForUserRow, error) {
	row := q.db.QueryRow(ctx, getPerkForUser, arg.ID, arg.UserID)
	var i GetPerkForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Unit,
		&i.Note,
		&i.CreatedAt,
		&i.BankClientID,
		&i.BankID,
		&i.ClientLabel,
		&i.BankName,
	)
	return i, err
}

const getPerkQuotaForUser = `-- name: GetPerkQuotaForUser :one
select q.id, q.perk_id, q.parent_quota_id, q.window_start, q.window_end, q.size, q.note, q.created_at, q.is_child, q.parent_is_root, p.user_id, p.bank_client_id, p.name as perk_name, p.unit
from perk_quota q
         join perk p on p.id = q.perk_id
where q.id = $1
  and p.user_id = $2
`

type GetPerkQuotaForUserParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetPerkQuotaForUserRow struct {
	ID            int64
	PerkID        int64
	ParentQuotaID *int64
	WindowStart   time.Time
	WindowEnd     time.Time
	Size          int32
	Note          *string
	CreatedAt     time.Time
	IsChild       pgtype.Bool
	ParentIsRoot  pgtype.Bool
	UserID        uuid.UUID
	BankClientID  int64
	PerkName      string
	Unit          string
}

func (q *Queries) GetPerkQuotaForUser(ctx context.Context, arg GetPerkQuotaForUserParams) (GetPerkQuotaForUserRow, error) {
	row := q.db.QueryRow(ctx, getPerkQuotaForUser, arg.ID, arg.UserID)
	var i GetPerkQuotaForUserRow
	err := row.Scan(
		&i.ID,
		&i.PerkID,
		&i.ParentQuotaID,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Size,
		&i.Note,
		&i.CreatedAt,
		&i.IsChild,
		&i.ParentIsRoot,
		&i.UserID,
		&i.BankClientID,
		&i.PerkName,
		&i.Unit,
	)
	return i, err
}

const listActivePerkQuotasForUser = `-- name: ListActivePerkQuotasForUser :many
select q.id, q.perk_id, q.parent_quota_id, q.window_start, q.window_end, q.size, q.note, q.created_at, q.is_child, q.parent_is_root,
       p.name    as perk_name,
       p.unit,
       p.note    as perk_note,
       cl.id     as client_id,
       cl.label  as client_label,
       b.id      as bank_id,
       b.name    as bank_name
from perk_quota q
         join perk p on p.id = q.perk_id
         join bank_client cl on cl.id = p.bank_client_id
         join bank b on b.id = cl.bank_id
where p.user_id = $1
  and (
    (q.window_start <= $2 and $2 <= q.window_end)
        or exists (select 1
                   from perk_quota c
                   where c.parent_quota_id = q.id
                     and c.window_start <= $2
                     and $2 <= c.window_end)
    )
order by b.name, cl.label nulls first, p.name, q.parent_quota_id nulls first, q.window_start
`

type ListActivePerkQuotasForUserParams struct {
	UserID uuid.UUID
	OnDate time.Time
}

type ListActivePerkQuotasForUserRow struct {
	ID            int64
	PerkID        int64
	ParentQuotaID *int64
	WindowStart   time.Time
	WindowEnd     time.Time
	Size          int32
	Note          *string
	CreatedAt     time.Time
	IsChild       pgtype.Bool
	ParentIsRoot  pgtype.Bool
	PerkName      string
	Unit          string
	PerkNote      *string
	ClientID      int64
	ClientLabel   *string
	BankID        int32
	BankName      string
}

// ListActivePerkQuotasForUser drives PV-01. A window counts as active when it
// contains the date, and so does a parent whose child is active — otherwise a
// monthly window running past its annual pool's end (ВТБ's program year does
// not follow Альфа's calendar year) would render as an orphan.
func (q *Queries) ListActivePerkQuotasForUser(ctx context.Context, arg ListActivePerkQuotasForUserParams) ([]ListActivePerkQuotasForUserRow, error) {
	rows, err := q.db.Query(ctx, listActivePerkQuotasForUser, arg.UserID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePerkQuotasForUserRow
	for rows.Next() {
		var i ListActivePerkQuotasForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PerkID,
			&i.ParentQuotaID,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Size,
			&i.Note,
			&i.CreatedAt,
			&i.IsChild,
			&i.ParentIsRoot,
			&i.PerkName,
			&i.Unit,
			&i.PerkNote,
			&i.ClientID,
			&i.ClientLabel,
			&i.BankID,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPerkSnapshots = `-- name: ListLatestPerkSnapshots :many
select distinct on (s.quota_id) s.id, s.quota_id, s.observed_on, s.remaining, s.note, s.created_at
from perk_snapshot s
where s.quota_id = any ($1::bigint[])
order by s.quota_id, s.observed_on desc, s.created_at desc
`

// ListLatestPerkSnapshots keeps one row per quota — the reading the discrepancy
// badge is judged against. created_at breaks a same-day tie in insert order, so
// correcting a mistyped snapshot is a matter of entering the right one.
func (q *Queries) ListLatestPerkSnapshots(ctx context.Context, quotaIds []int64) ([]PerkSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestPerkSnapshots, quotaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PerkSnapshot
	for rows.Next() {
		var i PerkSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.QuotaID,
			&i.ObservedOn,
			&i.Remaining,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerkEventsForPerk = `-- name: ListPerkEventsForPerk :many
select e.id,
       e.quota_id,
       e.kind,
       e.qty,
       e.event_date,
       e.note,
       e.created_at,
       q.parent_quota_id
from perk_event e
         join perk_quota q on q.id = e.quota_id
         join perk p on p.id = q.perk_id
where q.perk_id = $1
  and p.user_id = $2
order by e.event_date, e.id
`

type ListPerkEventsForPerkParams struct {
	PerkID int64
	UserID uuid.UUID
}

type ListPerkEventsForPerkRow struct {
	ID            int64
	QuotaID       int64
	Kind          PerkEventKind
	Qty           int32
	EventDate     time.Time
	Note          *string
	CreatedAt     time.Time
	ParentQuotaID *int64
}

func (q *Queries) ListPerkEventsForPerk(ctx context.Context, arg ListPerkEventsForPerkParams) ([]ListPerkEventsForPerkRow, error) {
	rows, err := q.db.Query(ctx, listPerkEventsForPerk, arg.PerkID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerkEventsForPerkRow
	for rows.Next() {
		var i ListPerkEventsForPerkRow
		if err := rows.Scan(
			&i.ID,
			&i.QuotaID,
			&i.Kind,
			&i.Qty,
			&i.EventDate,
			&i.Note,
			&i.CreatedAt,
			&i.ParentQuotaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerkEventsForQuotaTree = `-- name: ListPerkEventsForQuotaTree :many
select e.id,
       e.quota_id,
       e.kind,
       e.qty,
       e.event_date,
       e.note,
       e.created_at,
       q.parent_quota_id
from perk_event e
         join perk_quota q on q.id = e.quota_id
where q.id = any ($1::bigint[])
   or q.parent_quota_id = any ($1::bigint[])
order by e.event_date, e.id
`

type ListPerkEventsForQuotaTreeRow struct {
	ID            int64
	QuotaID       int64
	Kind          PerkEventKind
	Qty           int32
	EventDate     time.Time
	Note          *string
	CreatedAt     time.Time
	ParentQuotaID *int64
}

// ListPerkEventsForQuotaTree returns the events of the given quotas AND of
// their children: a leaf `use` burns both levels, so an annual window's
// remaining counts uses recorded on months that have long since closed and are
// nowhere near the active set. parent_quota_id rides along so the caller can
// attribute each row to its level without a second lookup.
func (q *Queries) ListPerkEventsForQuotaTree(ctx context.Context, quotaIds []int64) ([]ListPerkEventsForQuotaTreeRow, error) {
	rows, err := q.db.Query(ctx, listPerkEventsForQuotaTree, quotaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerkEventsForQuotaTreeRow
	for rows.Next() {
		var i ListPerkEventsForQuotaTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.QuotaID,
			&i.Kind,
			&i.Qty,
			&i.EventDate,
			&i.Note,
			&i.CreatedAt,
			&i.ParentQuotaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerkQuotasForPerk = `-- name: ListPerkQuotasForPerk :many
select q.id, q.perk_id, q.parent_quota_id, q.window_start, q.window_end, q.size, q.note, q.created_at, q.is_child, q.parent_is_root, cl.label as client_label, b.name as bank_name
from perk_quota q
         join perk p on p.id = q.perk_id
         join bank_client cl on cl.id = p.bank_client_id
         join bank b on b.id = cl.bank_id
where q.perk_id = $1
  and p.user_id = $2
order by coalesce(q.parent_quota_id, q.id), q.parent_quota_id nulls first, q.window_start desc
`

type ListPerkQuotasForPerkParams struct {
	PerkID int64
	UserID uuid.UUID
}

type ListPerkQuotasForPerkRow struct {
	ID            int64
	PerkID        int64
	ParentQuotaID *int64
	WindowStart   time.Time
	WindowEnd     time.Time
	Size          int32
	Note          *string
	CreatedAt     time.Time
	IsChild       pgtype.Bool
	ParentIsRoot  pgtype.Bool
	ClientLabel   *string
	BankName      string
}

// PV-02's history: every window of one perk, newest first. Children sort
// directly under their parent's window, so the screen can render the tree
// without a second pass.
func (q *Queries) ListPerkQuotasForPerk(ctx context.Context, arg ListPerkQuotasForPerkParams) ([]ListPerkQuotasForPerkRow, error) {
	rows, err := q.db.Query(ctx, listPerkQuotasForPerk, arg.PerkID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerkQuotasForPerkRow
	for rows.Next() {
		var i ListPerkQuotasForPerkRow
		if err := rows.Scan(
			&i.ID,
			&i.PerkID,
			&i.ParentQuotaID,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Size,
			&i.Note,
			&i.CreatedAt,
			&i.IsChild,
			&i.ParentIsRoot,
			&i.ClientLabel,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerkSnapshotsForPerk = `-- name: ListPerkSnapshotsForPerk :many
select s.id, s.quota_id, s.observed_on, s.remaining, s.note, s.created_at
from perk_snapshot s
         join perk_quota q on q.id = s.quota_id
         join perk p on p.id = q.perk_id
where q.perk_id = $1
  and p.user_id = $2
order by s.observed_on desc, s.created_at desc
`

type ListPerkSnapshotsForPerkParams struct {
	PerkID int64
	UserID uuid.UUID
}

func (q *Queries) ListPerkSnapshotsForPerk(ctx context.Context, arg ListPerkSnapshotsForPerkParams) ([]PerkSnapshot, error) {
	rows, err := q.db.Query(ctx, listPerkSnapshotsForPerk, arg.PerkID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PerkSnapshot
	for rows.Next() {
		var i PerkSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.QuotaID,
			&i.ObservedOn,
			&i.Remaining,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerksForUser = `-- name: ListPerksForUser :many
select p.id, p.user_id, p.name, p.unit, p.note, p.created_at, p.bank_client_id, cl.bank_id, cl.label as client_label, b.name as bank_name
from perk p
         join bank_client cl on cl.id = p.bank_client_id
         join bank b on b.id = cl.bank_id
where p.user_id = $1
order by b.name, cl.label nulls first, p.name
`

type ListPerksForUserRow struct {
	ID           int64
	UserID       uuid.UUID
	Name         string
	Unit         string
	Note         *string
	CreatedAt    time.Time
	BankClientID int64
	BankID       int32
	ClientLabel  *string
	BankName     string
}

func (q *Queries) ListPerksForUser(ctx context.Context, userID uuid.UUID) ([]ListPerksForUserRow, error) {
	rows, err := q.db.Query(ctx, listPerksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerksForUserRow
	for rows.Next() {
		var i ListPerksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Unit,
			&i.Note,
			&i.CreatedAt,
			&i.BankClientID,
			&i.BankID,
			&i.ClientLabel,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerkForUser = `-- name: UpdatePerkForUser :one
update perk
set name = coalesce($1, name),
    unit = coalesce($2, unit),
    note = case when $3::boolean then $4 else note end
where id = $5
  and user_id = $6
returning id, user_id, name, unit, note, created_at, bank_client_id
`

type UpdatePerkForUserParams struct {
	Name    *string
	Unit    *string
	SetNote bool
	Note    *string
	ID      int64
	UserID  uuid.UUID
}

// UpdatePerkForUser patches the three editable fields; a null argument leaves
// its column alone, so the caller sends only what changed.
func (q *Queries) UpdatePerkForUser(ctx context.Context, arg UpdatePerkForUserParams) (Perk, error) {
	row := q.db.QueryRow(ctx, updatePerkForUser,
		arg.Name,
		arg.Unit,
		arg.SetNote,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i Perk
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Unit,
		&i.Note,
		&i.CreatedAt,
		&i.BankClientID,
	)
	return i, err
}

const updatePerkQuotaForUser = `-- name: UpdatePerkQuotaForUser :one
update perk_quota q
set size = coalesce($1, q.size),
    note = case when $2::boolean then $3 else q.note end
from perk p
where p.id = q.perk_id
  and q.id = $4
  and p.user_id = $5
returning q.id, q.perk_id, q.parent_quota_id, q.window_start, q.window_end, q.size, q.note, q.created_at, q.is_child, q.parent_is_root
`

type UpdatePerkQuotaForUserParams struct {
	Size    *int32
	SetNote bool
	Note    *string
	ID      int64
	UserID  uuid.UUID
}

// `size` is patchable only while the window has no history (spec invariant 5);
// the service checks that and passes null otherwise.
func (q *Queries) UpdatePerkQuotaForUser(ctx context.Context, arg UpdatePerkQuotaForUserParams) (PerkQuotum, error) {
	row := q.db.QueryRow(ctx, updatePerkQuotaForUser,
		arg.Size,
		arg.SetNote,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i PerkQuotum
	err := row.Scan(
		&i.ID,
		&i.PerkID,
		&i.ParentQuotaID,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Size,
		&i.Note,
		&i.CreatedAt,
		&i.IsChild,
		&i.ParentIsRoot,
	)
	return i, err
}
